(function(K){
  'use strict';
  var playerState={type:'idle',start:0,duration:1,facing:'right',facingId:'S'},enemyStates=new WeakMap(),projectiles=[],deaths=[],running=false;
  function now(){return typeof performance!=='undefined'?performance.now():Date.now();}
  function stateOf(s,t){var elapsed=t-s.start;if(s.type!=='death'&&elapsed>=s.duration)return{type:'idle',progress:0};return{type:s.type,progress:Math.max(0,Math.min(1,elapsed/s.duration))};}
  function pushProjectile(kind,category,from,direction,path,hit,wall){var travel=Math.max(70,path.length*48);projectiles.push({kind:kind,category:category,start:now(),from:{x:from.x,y:from.y},direction:{dx:direction.dx,dy:direction.dy},path:path,travel:travel,duration:travel+130,hit:!!hit,wall:!!wall});if(projectiles.length>8)projectiles.shift();}
  function launch(state,kind,item){var p=state.player,f=p.facingDirection||{dx:0,dy:1},path=[],hit=false,wall=false,pierce=kind==='arrow'&&item&&item.effect==='pierce';for(var n=1;n<=10;n++){var x=p.x+f.dx*n,y=p.y+f.dy*n;if(!K.Map.walkable(state,x,y)){wall=true;break;}path.push({x:x,y:y});if(state.enemies.some(function(e){return e.x===x&&e.y===y;})){hit=true;if(!pierce)break;}}pushProjectile(kind,item&&item.category,p,f,path,hit,wall);}
  function launchFromEnemy(state,enemy,kind){var p=state.player,dx=Math.sign(p.x-enemy.x),dy=Math.sign(p.y-enemy.y),path=[],hit=false,wall=false;for(var n=1;n<=10;n++){var x=enemy.x+dx*n,y=enemy.y+dy*n;if(!K.Map.walkable(state,x,y)){wall=true;break;}path.push({x:x,y:y});if(x===p.x&&y===p.y){hit=true;break;}}pushProjectile(kind||'enemyFire',null,enemy,{dx:dx,dy:dy},path,hit,wall);}
  function projectileFrames(t){var frames=[];projectiles=projectiles.filter(function(q){var elapsed=t-q.start;if(elapsed>=q.duration)return false;var travelProgress=Math.min(1,elapsed/q.travel),scaled=travelProgress*q.path.length,whole=Math.floor(scaled),previous=whole<=0?q.from:q.path[Math.min(whole-1,q.path.length-1)],next=q.path[Math.min(whole,q.path.length-1)]||q.from,local=whole>=q.path.length?1:scaled-whole,x=previous.x+(next.x-previous.x)*local,y=previous.y+(next.y-previous.y)*local;frames.push({kind:q.kind,category:q.category,x:x,y:y,dx:q.direction.dx,dy:q.direction.dy,impact:elapsed>q.travel?(elapsed-q.travel)/(q.duration-q.travel):0,hit:q.hit,wall:q.wall});return true;});return frames;}
  function loop(t){if(K.State&&K.State.data&&K.State.data.map.length&&K.UI&&K.UI.renderAnimationFrame)K.UI.renderAnimationFrame(K.State.data,t);requestAnimationFrame(loop);}
  K.Animation={player:function(type,duration,direction){var id=direction&&K.Direction8&&K.Direction8.fromDelta(direction.dx,direction.dy);if(id){playerState.facingId=id;var side=K.Direction8.side(id);if(side!=='center')playerState.facing=side;}else if(direction&&direction.dx)playerState.facing=direction.dx<0?'left':'right';playerState.type=type;playerState.start=now();playerState.duration=duration||240;playerState.move=type==='walk'&&direction?{dx:(direction.fromX||0)-(direction.toX||0),dy:(direction.fromY||0)-(direction.toY||0)}:null;},enemy:function(enemy,type,duration,motion){if(enemy&&motion&&K.Direction8)K.Direction8.apply(enemy,motion.dx,motion.dy);enemyStates.set(enemy,{type:type,start:now(),duration:duration||220,move:type==='walk'&&motion?{dx:(motion.fromX||0)-(motion.toX||0),dy:(motion.fromY||0)-(motion.toY||0)}:null,direction:motion||null});},enemyDeath:function(enemy){var current=now(),delay=0;projectiles.forEach(function(q){var index=q.path.findIndex(function(p){return p.x===enemy.x&&p.y===enemy.y;});if(index>=0){var arrival=q.travel*(index+1)/Math.max(1,q.path.length)+70-(current-q.start);delay=Math.max(delay,arrival);}});deaths.push({enemy:Object.assign({},enemy),start:current+Math.max(0,delay),duration:420});if(deaths.length>8)deaths.shift();},launch:launch,launchFromEnemy:launchFromEnemy,playerFrame:function(t){var f=stateOf(playerState,t),move=playerState.move;if(f.type==='walk'&&move){f.offsetX=move.dx*(1-f.progress);f.offsetY=move.dy*(1-f.progress);}else{f.offsetX=0;f.offsetY=0;}f.facing=playerState.facing;f.facingId=playerState.facingId;return f;},enemyFrame:function(enemy,t){var s=enemyStates.get(enemy),f=s?stateOf(s,t):{type:'idle',progress:0};if(s&&f.type==='walk'&&s.move){f.offsetX=s.move.dx*(1-f.progress);f.offsetY=s.move.dy*(1-f.progress);}else{f.offsetX=0;f.offsetY=0;}if(s&&s.direction){f.dx=s.direction.dx||0;f.dy=s.direction.dy||0;f.facingId=K.Direction8&&K.Direction8.fromDelta(f.dx,f.dy);}else if(K.Direction8){f.facingId=K.Direction8.fromActor(enemy);}return f;},deathFrames:function(t){var result=[];deaths=deaths.filter(function(d){var p=(t-d.start)/d.duration;if(p>=1)return false;result.push({enemy:d.enemy,progress:Math.max(0,p),pending:p<0});return true;});return result;},projectileFrames:projectileFrames,clearProjectiles:function(){projectiles.length=0;},start:function(){if(running||typeof requestAnimationFrame==='undefined')return;running=true;requestAnimationFrame(loop);}};
  addEventListener('DOMContentLoaded',function(){K.Animation.start();});
})(window.Kiri=window.Kiri||{});
