(function(K){'use strict';var U=K.Util,legacyBehaviors=['wander','chaser','sleeper','fast','slow','ranged','coward','thief'];
function gain(s,n){
  if(K.Progression)return K.Progression.addExp(s.player,n);
  var p=s.player,levels=[];
  p.exp=(p.exp||0)+n;
  while(p.exp>=p.level*10){var hpGain=3;p.level++;p.maxHp+=hpGain;p.hp=Math.min(p.maxHp,(p.hp||0)+hpGain);levels.push(p.level);}
  return levels;
}
function canLandItem(s,x,y,e){if(K.ProjectileLanding&&K.ProjectileLanding.canLand)return K.ProjectileLanding.canLand(s,x,y);return K.Map.walkable(s,x,y)&&!s.groundItems.some(function(q){return q.x===x&&q.y===y;})&&!s.enemies.some(function(q){return q!==e&&q.x===x&&q.y===y;})&&!(s.player.x===x&&s.player.y===y)&&!(s.stairs&&s.stairs.x===x&&s.stairs.y===y)&&!(s.traps||[]).some(function(t){return t.x===x&&t.y===y;});}
function dropCell(s,e){var cells=U.shuffle([[0,0],[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]);for(var i=0;i<cells.length;i++){var x=e.x+cells[i][0],y=e.y+cells[i][1];if(canLandItem(s,x,y,e))return{x:x,y:y};}return null;}
function itemForCategory(s,category){if(category==='goodFood'){var foods=['nutBread','bigBread'].filter(function(id){return K.Items.definitions[id];});return foods.length?foods[U.rand(foods.length)]:null;}var categories=category==='rare'?['ring','staff','weapon','shield']:category==='treasure'||category==='random'?['food','herb','scroll','staff','arrow','weapon','shield','ring']:[category],ids=Object.keys(K.Items.definitions).filter(function(id){var d=K.Items.definitions[id];if(categories.indexOf(d.category)<0)return false;if(s.floor<15&&d.basePower>5)return false;return true;});return ids.length?ids[U.rand(ids.length)]:null;}
function enemyDrop(s,e){if(Math.random()>=(e.dropRate||0))return'';var categories=e.dropCategories&&e.dropCategories.length?e.dropCategories:['random'],category=categories[U.rand(categories.length)];if(category==='gold'){var gold=K.Gold&&K.Gold.amountForFloor?K.Gold.amountForFloor(s.floor):1+U.rand(100),goldCell=dropCell(s,e);if(goldCell&&K.Gold&&K.Gold.dropAt){K.Gold.dropAt(s,gold,goldCell.x,goldCell.y);return e.name+'は'+gold+'Gを落とした。';}return'';}var cell=dropCell(s,e),id=itemForCategory(s,category);if(!cell||!id)return'';var item=K.Items.create(id,cell.x,cell.y,s.dungeonId);s.groundItems.push(item);return e.name+'は'+K.Items.name(item)+'を落とした。';}
function rewardDefeat(s,e,awardExp){if(e.rewarded)return{exp:0,levels:[],text:'',drop:''};e.rewarded=true;var exp=awardExp?(e.exp||0):0,levels=awardExp?gain(s,exp):[],index=s.enemies.indexOf(e);if(index>=0)s.enemies.splice(index,1);if(e.stolenItem){var stolenCell=dropCell(s,e);if(stolenCell){e.stolenItem.x=stolenCell.x;e.stolenItem.y=stolenCell.y;s.groundItems.push(e.stolenItem);}}var drop=enemyDrop(s,e),text=awardExp?exp+'ポイントの経験値を得た。':'';levels.forEach(function(level){text+=' レベルが'+level+'に上がった！';});if(drop)text+=' '+drop;if(K.Animation&&K.Animation.enemyDeath)K.Animation.enemyDeath(e);return{exp:exp,levels:levels,text:text,drop:drop};}
function sleepChance(floor,behavior){var chance=floor<=5?.45:floor<=15?.28:floor<=30?.16:.1;if(behavior==='sleeper')chance=Math.max(chance,.72);return chance;}
function scaledAttack(d,f,m){var mult=m?m.enemyPowerMultiplier:1;return Math.max(1,Math.floor(d.attack*mult));}
function canOccupy(s,e,x,y){if(x<0||y<0||x>=K.Config.width||y>=K.Config.height)return false;var dx=x-e.x,dy=y-e.y;if(e.specialAbility!=='phase'&&!K.Map.canTraverse(s,e,x,y,dx,dy))return false;return!(x===s.player.x&&y===s.player.y)&&!s.enemies.some(function(o){return o!==e&&o.x===x&&o.y===y;});}
function face(e,dx,dy){if(K.Direction8)K.Direction8.apply(e,dx,dy);else if(dx||dy)e.facingDirection={dx:Math.sign(dx),dy:Math.sign(dy)};}
function facePlayer(e,s){face(e,s.player.x-e.x,s.player.y-e.y);}
function freeMove(s,e,choices){return choices.some(function(v){var x=e.x+v[0],y=e.y+v[1];if(!canOccupy(s,e,x,y))return false;face(e,v[0],v[1]);e.x=x;e.y=y;return true;});}
function toward(e,p,away){var dx=Math.sign(p.x-e.x),dy=Math.sign(p.y-e.y),moves=[];if(away){dx=-dx;dy=-dy;}if(dx&&dy)moves.push([dx,dy]);if(dx)moves.push([dx,0]);if(dy)moves.push([0,dy]);return moves.concat(U.shuffle([[1,0],[-1,0],[0,1],[0,-1]]));}
function lineClear(s,e,range){var p=s.player,dx=Math.sign(p.x-e.x),dy=Math.sign(p.y-e.y),ax=Math.abs(p.x-e.x),ay=Math.abs(p.y-e.y);if(e.x!==p.x&&e.y!==p.y&&ax!==ay)return false;if(U.distance(e,p)>range)return false;for(var x=e.x+dx,y=e.y+dy;x!==p.x||y!==p.y;x+=dx,y+=dy){if(!K.Map.walkable(s,x,y))return false;if(s.enemies.some(function(o){return o!==e&&o.x===x&&o.y===y;}))return false;}return true;}
function sameRoom(s,a,b){return s.rooms.some(function(r){return a.x>=r.x&&a.x<r.x+r.w&&a.y>=r.y&&a.y<r.y+r.h&&b.x>=r.x&&b.x<r.x+r.w&&b.y>=r.y&&b.y<r.y+r.h;});}
function chance(e,key,fallback){return e[key]!==undefined?e[key]:(e.specialChance!==undefined?e.specialChance:fallback);}
function rollSpecial(e,key,fallback){if(e.specialCooldownLeft>0)return false;var ok=Math.random()<chance(e,key,fallback);if(ok&&e.specialCooldown)e.specialCooldownLeft=e.specialCooldown;return ok;}
function gazeBlocked(p){var st=p.status||{};return(st.confuse||0)>0||(st.blind||0)>0||(st.invisible||0)>0;}
function specialReach(s,e){return sameRoom(s,e,s.player)||K.CombatRules.canMeleeAttack(s,e,s.player);}
function confuseGaze(s,e){if(gazeBlocked(s.player)||!specialReach(s,e)||!rollSpecial(e,'confuseChance',.25))return false;facePlayer(e,s);s.player.status.confuse=e.statusDuration||7;e.aiState='にらみ';K.State.addLog(e.name+'のにらみで混乱した。');return true;}
function rangedDamage(s,e,kind){facePlayer(e,s);if(K.Animation&&K.Animation.launchFromEnemy)K.Animation.launchFromEnemy(s,e,kind==='fire'?'enemyFire':'wand');var raw=e.rangedDamage|| (kind==='fire'?10:4+Math.floor(s.floor/6));if(kind==='fire'&&K.Items.hasEffect(s,'fireHalf'))raw=Math.floor(raw/2);var hit=Math.max(1,raw-K.Items.defensePower(s));s.player.hp-=hit;K.State.addLog(e.name+'が'+(kind==='fire'?'炎':'光弾')+'を放ち、'+hit+'のダメージ。');}
function weakenGear(s,e){var choices=[s.player.equipment.shield,s.player.equipment.weapon].filter(Boolean);var gear=choices.length?choices[U.rand(choices.length)]:null;if(!gear)return false;if(gear.effect==='rustProof'){K.State.addLog(gear.trueName+'が弱化を防いだ。');return false;}gear.modifier--;gear.bonus--;K.State.addLog(e.name+'の一撃で '+gear.trueName+'が弱くなった。');return true;}
function applyTouch(s,e){var p=s.player,a=e.specialAbility,dur=e.statusDuration||0;if(a==='poisonTouch'&&rollSpecial(e,'poisonChance',.35)){if(K.PlayerVitals)K.PlayerVitals.applyStrengthDamage(s,1,e.name+'の毒');else p.power=Math.max(0,(p.power||8)-1);}else if(a==='sleepTouch'&&rollSpecial(e,'sleepChance',.3)&&!K.Items.hasEffect(s,'sleepGuard')&&!(p.status.sleep>0)){p.status.sleep=dur||4;K.State.addLog(e.name+'の冷気で眠りに落ちた。');}else if(a==='confuseTouch'&&rollSpecial(e,'confuseChance',.35)&&!(p.status.confuse>0)){p.status.confuse=dur||7;K.State.addLog(e.name+'の眼差しで混乱した。');}else if(a==='weakenGear'&&rollSpecial(e,'rustChance',.35))weakenGear(s,e);else if(a==='hungerDrain'&&rollSpecial(e,'specialChance',.4)&&p.food>0){var n=e.hungerDamage||12;p.food=Math.max(0,p.food-n);K.State.addLog(e.name+'に満腹度を'+n+'奪われた。');}}
function attackPlayer(s,e){facePlayer(e,s);var raw=Math.max(1,e.power-U.rand(2)),hit=Math.max(1,raw-K.Items.defensePower(s));s.player.hp-=hit;K.State.addLog(e.name+'から '+hit+' のダメージ。');applyTouch(s,e);}
function steal(s,e){facePlayer(e,s);if(!s.inventory.length||!rollSpecial(e,'specialChance',.28))return false;var choices=s.inventory.filter(function(i){return!i.equipped&&!i.important;});if(!choices.length)return false;var item=choices[U.rand(choices.length)];s.inventory.splice(s.inventory.indexOf(item),1);e.stolenItem=item;e.fleeing=true;e.wokeOnTurn=s.turn;K.State.addLog(e.name+'に '+K.Items.name(item)+'を盗まれた！');return true;}
function split(s,e){if(s.enemies.length>=s.spawnPolicy.maxEnemies||!rollSpecial(e,'splitChance',.35))return;if(!K.EnemyCatalog.canSpawnMore(s,K.EnemyCatalog.get(e.definitionId)))return;var cells=U.shuffle([[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]);for(var i=0;i<cells.length;i++){var x=e.x+cells[i][0],y=e.y+cells[i][1];if(canLandItem(s,x,y,e)){var clone=K.Entities.createEnemy(s.floor,{x:x,y:y},K.Dungeons.get(s.dungeonId),e.definitionId);clone.hp=Math.max(1,Math.floor(e.hp/2));clone.maxHp=e.maxHp;clone.wokeOnTurn=s.turn;clone.spawnedTurn=s.turn;clone.splitParent=e.id||e.definitionId;s.enemies.push(clone);K.State.addLog(e.name+'が二つに分かれた！');return;}}}
function staffCast(s,e){facePlayer(e,s);var p=s.player,r=U.rand(3),dur=e.statusDuration||6;if(r===0&&!(p.status.confuse>0)){p.status.confuse=dur;K.State.addLog(e.name+'が迷いの術を放った。');}else if(r===1&&!K.Items.hasEffect(s,'sleepGuard')&&!(p.status.sleep>0)){p.status.sleep=Math.max(3,Math.floor(dur/2));K.State.addLog(e.name+'が眠りの術を放った。');}else{p.hungerClock+=3;K.State.addLog(e.name+'が古い重圧をまとわせた。');}}
K.Entities={behaviors:legacyBehaviors,createEnemy:function(f,p,m,forced){var forcedDef=K.EnemyCatalog.byId[forced],d=forcedDef||K.EnemyCatalog.pick(m&&m.id||'normalDungeon',f),behavior=forcedDef?d.behaviorType:(legacyBehaviors.indexOf(forced)>=0?forced:d.behaviorType),speed=behavior==='fast'?2:behavior==='slow'?.5:1,spawnSleep=forced===undefined?Math.random()<(d.spawnSleepChance!==undefined?d.spawnSleepChance:sleepChance(f,behavior)):behavior==='sleeper',hp=Math.max(1,Math.round(d.hp*(m&&m.enemyHpMultiplier||1))),enemy={x:p.x,y:p.y,definitionId:d.id,spriteId:d.id,name:d.name,hp:hp,maxHp:hp,power:scaledAttack(d,f,m),defense:Math.max(0,Math.round(d.defense*(m&&m.enemyDefenseMultiplier||1))),exp:d.exp,dropRate:d.dropRate,dropCategories:d.dropCategories.slice(),behaviorType:behavior,specialAbility:d.specialAbility,role:d.role,color:d.color,iconShape:d.iconShape,description:d.description,speed:speed,energy:0,spawnSleep:spawnSleep,effectSleep:0,awake:!spawnSleep,fleeing:false,stolenItem:null,status:{sleep:0,confuse:0,poison:0,bind:0,blind:0},aiState:'生成',splitCount:0,specialCooldownLeft:0,facingDirection:{dx:0,dy:1,id:'S'},facing8:'S'};['spawnWeight','maxPerFloor','specialChance','specialCooldown','specialRange','statusDuration','rangedDamage','hungerDamage','stealType','splitChance','warpChance','rustChance','sleepChance','confuseChance','poisonChance','spawnSleepChance'].forEach(function(k){if(d[k]!==undefined)enemy[k]=d[k];});return enemy;},
rewardDefeat:rewardDefeat,
attack:function(s,e){e.spawnSleep=false;e.awake=true;var d=Math.max(1,K.Items.attackPower(s)+U.rand(3)-1-(e.defense||0)),message=e.name+'に'+d+'ダメージを与えた。';e.hp-=d;if(e.hp<=0){var reward=rewardDefeat(s,e,true);K.State.addLog(message+e.name+'を倒した。 '+reward.text);return;}K.State.addLog(message);if(e.specialAbility==='split')split(s,e);if(e.specialAbility==='warpHit'&&rollSpecial(e,'warpChance',.35)){K.ItemActions.warpEntity(s,e);e.wokeOnTurn=s.turn;K.State.addLog(e.name+'は裂け目へ逃げ込んだ。');}},
takeEnemyTurns:function(s){s.enemies.slice().forEach(function(e){e.status=e.status||{sleep:0,confuse:0,poison:0,bind:0};if(e.wokeOnTurn===s.turn){e.energy=0;return;}if(e.status.poison>0){e.status.poison--;if(e.status.poison%3===0)e.hp--;}if(e.hp<=0)return;e.energy=(e.energy||0)+(e.speed||1);while(e.energy>=1&&s.player.hp>0&&e.hp>0){var outcome=K.Entities.enemyAct(s,e);e.energy-=1;if(outcome==='woke'||outcome==='sleeping'){e.energy=0;break;}}});s.enemies=s.enemies.filter(function(e){return e.hp>0;});},
enemyAct:function(s,e){var status=e.status,p=s.player,d=U.distance(e,p),adjacent=K.CombatRules.canMeleeAttack(s,e,p),effect=Math.max(e.effectSleep||0,status.sleep||0),range=e.specialRange||7;if(e.specialCooldownLeft>0)e.specialCooldownLeft--;if(e.wokeOnTurn===s.turn)return'woke';if(effect>0){effect--;e.effectSleep=effect;status.sleep=effect;if(effect===0){e.spawnSleep=false;e.awake=true;e.wokeOnTurn=s.turn;e.aiState='起床';K.State.addLog(e.name+'は目を覚ました。');return'woke';}e.aiState='睡眠中';return'sleeping';}if(e.spawnSleep||!e.awake){if((d<=2&&Math.random()<.35)||(K.Visibility.enemyCanSee(s,e,p)&&Math.random()<.05)){e.spawnSleep=false;e.awake=true;e.wokeOnTurn=s.turn;e.aiState='起床';K.State.addLog(e.name+'は目を覚ました。');return'woke';}e.aiState='睡眠中';return'sleeping';}if(status.confuse>0){status.confuse--;e.aiState='混乱移動';return freeMove(s,e,U.shuffle([[1,0],[-1,0],[0,1],[0,-1],[0,0]]));}if(status.blind>0){status.blind--;e.aiState='目つぶし';return freeMove(s,e,U.shuffle([[1,0],[-1,0],[0,1],[0,-1],[0,0]]));}if(status.bind>0){status.bind--;e.aiState='停止';if(adjacent&&K.Map.walkable(s,e.x,e.y))attackPlayer(s,e);return;}if(!K.Visibility.enemyCanSee(s,e,p)){e.aiState='索敵';return freeMove(s,e,U.shuffle([[1,0],[-1,0],[0,1],[0,-1],[0,0]]));}if(e.specialAbility==='confuseGaze'&&confuseGaze(s,e))return;if(e.specialAbility==='roomShot'&&sameRoom(s,e,p)&&rollSpecial(e,'specialChance',.5)){e.aiState='部屋攻撃';rangedDamage(s,e,'light');return;}if(e.specialAbility==='fireBreath'&&lineClear(s,e,range)&&rollSpecial(e,'specialChance',.55)){e.aiState='炎攻撃';rangedDamage(s,e,'fire');return;}if(e.specialAbility==='staffCast'&&specialReach(s,e)&&rollSpecial(e,'specialChance',.45)){e.aiState='杖術';staffCast(s,e);return;}if(e.behaviorType==='ranged'&&lineClear(s,e,range)&&rollSpecial(e,'specialChance',.72)){e.aiState='遠距離攻撃';rangedDamage(s,e,'light');return;}if(adjacent){if(!K.Map.walkable(s,e.x,e.y)){e.aiState='壁から出る';var out=toward(e,p,false).concat(U.shuffle([[1,0],[-1,0],[0,1],[0,-1]]));freeMove(s,e,out);return;}if(e.behaviorType==='thief'&&!e.fleeing&&steal(s,e)){e.aiState='盗み';return;}e.aiState='通常攻撃';attackPlayer(s,e);return;}var away=e.fleeing||(e.behaviorType==='coward'&&e.hp<e.maxHp/2),choices;if(away){e.aiState='逃走';choices=toward(e,p,true);}else if(e.behaviorType==='wander'&&d>5){e.aiState='ふらふら';choices=U.shuffle([[1,0],[-1,0],[0,1],[0,-1],[0,0]]);}else{e.aiState='追跡';choices=toward(e,p,false);}freeMove(s,e,choices);}}
var baseEnemyAct=K.Entities.enemyAct;
K.Entities.enemyAct=function(s,e){var status=e.status||{},p=s.player,effect=Math.max(e.effectSleep||0,status.sleep||0);if(e.wokeOnTurn!==s.turn&&effect<=0&&!(e.spawnSleep||!e.awake)&&!(status.confuse>0)&&!(status.blind>0)&&!(status.bind>0)&&!K.Visibility.enemyCanSee(s,e,p)){if(e.behaviorType==='wander'){e.aiState='ふらふら';return freeMove(s,e,U.shuffle([[1,0],[-1,0],[0,1],[0,-1],[0,0]]));}e.aiState='追跡';return freeMove(s,e,toward(e,p,false));}return baseEnemyAct(s,e);};
;})(window.Kiri=window.Kiri||{});
