(function(K){
  'use strict';
  var C=K.Config,DEBUG=K.DEBUG_MODE===true,mode=DEBUG&&readStoredMode()==='gm'?'gm':'normal';
  var gmLog=[],panel=null,open=false,selectedEnemyId='',selectedItemId='',targetMode='frontEnemy';
  var flags={log:true,enemyStop:false,enemyAIStop:false,noHunger:false,noRecovery:false,freezeStatuses:false,invincible:false,wallWalk:false,allIdentified:false,uncurse:false,alwaysHit:false,enemyAttackOff:false,noExp:false,dropAlways:false,dropNever:false,overlayVision:false,overlayMove:false,photo:false,hideStatus:false,hideMessage:false,hideMinimap:false,hideControls:false,hideArrow:false};
  function readStoredMode(){try{var stored=localStorage.getItem(C.modeKey),keys=C.legacyModeKeys||[];for(var i=0;!stored&&i<keys.length;i++)stored=localStorage.getItem(keys[i]);return stored;}catch(e){return null;}}
  function active(){return DEBUG&&mode==='gm'&&K.State&&K.State.data&&K.State.data.gmMode===true;}
  function saveMode(){try{localStorage.setItem(C.modeKey,mode);}catch(e){}}
  function saveKey(){return mode==='gm'?C.gmSaveKey:C.normalSaveKey;}
  function log(msg,tag){if(!active()||!flags.log)return;gmLog.unshift({text:msg,tag:tag||'AI',time:new Date().toLocaleTimeString()});gmLog.length=Math.min(gmLog.length,120);renderLog();}
  function clamp(n,min,max){n=Number(n);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):min;}
  function state(){return K.State.data;}
  function p(){return state().player;}
  function key(x,y){return K.Util.key(x,y);}
  function frontCell(dist){var pl=p(),f=pl.facingDirection||{dx:0,dy:1};dist=dist||1;return{x:pl.x+f.dx*dist,y:pl.y+f.dy*dist};}
  function clearOccupation(s,x,y){return K.Map.walkable(s,x,y)&&!(s.player.x===x&&s.player.y===y)&&!s.enemies.some(function(e){return e.x===x&&e.y===y;});}
  function canPlaceItem(s,x,y){return K.Map.walkable(s,x,y)&&!(s.player.x===x&&s.player.y===y)&&!s.enemies.some(function(e){return e.x===x&&e.y===y;})&&!s.groundItems.some(function(i){return i.x===x&&i.y===y;});}
  function aroundCells(s){var pl=p(),cells=[];for(var dy=-1;dy<=1;dy++)for(var dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;var x=pl.x+dx,y=pl.y+dy;if(clearOccupation(s,x,y))cells.push({x:x,y:y});}return cells;}
  function sameRoomCells(s){var pl=p(),room=s.rooms.find(function(r){return pl.x>=r.x&&pl.x<r.x+r.w&&pl.y>=r.y&&pl.y<r.y+r.h;}),cells=[];if(!room)return cells;for(var y=room.y;y<room.y+room.h;y++)for(var x=room.x;x<room.x+room.w;x++)if(clearOccupation(s,x,y))cells.push({x:x,y:y});return cells;}
  function randomCell(cells){return cells.length?cells[K.Util.rand(cells.length)]:null;}
  function seeded(seed,fn){if(seed===''||seed===null||seed===undefined)return fn();var n=String(seed).split('').reduce(function(a,ch){return(a*31+ch.charCodeAt(0))>>>0;},2166136261),old=Math.random;Math.random=function(){n=(n*1664525+1013904223)>>>0;return n/4294967296;};try{return fn();}finally{Math.random=old;}}
  function allVisible(s){for(var y=0;y<C.height;y++)for(var x=0;x<C.width;x++)if(s.map[y]&&s.map[y][x])s.seen[key(x,y)]=1;}
  function sync(){if(K.Map&&K.Map.reveal)K.Map.reveal(state());if(K.UI&&K.UI.draw)K.UI.draw(state());if(panel)renderPanel();}
  function categoryName(c){return{weapon:'武器',shield:'盾',staff:'杖',ring:'指輪',herb:'草',scroll:'紙片',food:'パン',arrow:'矢'}[c]||c;}
  function visibleItemIds(){return Object.keys(K.Items.definitions).sort(function(a,b){var da=K.Items.definitions[a],db=K.Items.definitions[b];return categoryName(da.category).localeCompare(categoryName(db.category),'ja')||da.trueName.localeCompare(db.trueName,'ja');});}
  function makeItem(id,x,y){var item=K.Items.create(id,x,y,state().dungeonId),d=K.Items.definitions[id];if(!item)return null;item.identified=document.querySelector('[data-gm-item-identified]')?document.querySelector('[data-gm-item-identified]').checked:true;if(item.identified)item.displayName=item.trueName;item.cursed=!!(document.querySelector('[data-gm-item-cursed]')&&document.querySelector('[data-gm-item-cursed]').checked);item.curseKnown=true;if(item.category==='weapon'||item.category==='shield'){var mod=clamp(document.querySelector('[data-gm-item-mod]').value,-9,99);item.modifier=mod;item.bonus=(d.basePower||0)+mod;}if(item.category==='staff'){item.charges=clamp(document.querySelector('[data-gm-item-charges]').value,0,99);item.chargesKnown=true;}if(item.category==='arrow')item.quantity=clamp(document.querySelector('[data-gm-item-qty]').value,1,99);return item;}
  function addItem(where,id){var s=state(),item,cell;if(!id)id=selectedItemId;if(!id)return false;if(where==='bag'){item=makeItem(id);if(!item)return false;if(s.inventory.length>=C.inventoryMax&&item.category!=='arrow'){log('道具袋がいっぱいです。','アイテム');return false;}s.inventory.push(item);if(K.Inventory)K.Inventory.sort(s);log(K.Items.name(item)+'を道具袋へ追加。','アイテム');sync();return true;}if(where==='front')cell=frontCell();else if(where==='coord')cell={x:clamp(document.querySelector('[data-gm-x]').value,0,C.width-1),y:clamp(document.querySelector('[data-gm-y]').value,0,C.height-1)};else cell={x:s.player.x,y:s.player.y};if(!canPlaceItem(s,cell.x,cell.y)){log('配置できる床がありません。','アイテム');return false;}item=makeItem(id,cell.x,cell.y);s.groundItems.push(item);log(K.Items.name(item)+'を床へ配置。','アイテム');sync();return true;}
  function addAllItems(){visibleItemIds().forEach(function(id){if(state().inventory.length<C.inventoryMax)addItem('bag',id);});log('道具袋の上限まで全アイテムを追加しました。','アイテム');sync();}
  function enemyCell(where){var s=state();if(where==='around')return randomCell(aroundCells(s));if(where==='room')return randomCell(sameRoomCells(s));if(where==='coord')return{x:clamp(document.querySelector('[data-gm-x]').value,0,C.width-1),y:clamp(document.querySelector('[data-gm-y]').value,0,C.height-1)};return frontCell();}
  function spawnEnemy(where){var s=state(),cell=enemyCell(where),id=selectedEnemyId||K.EnemyCatalog.list[0].id;if(!cell||!clearOccupation(s,cell.x,cell.y)){log('敵を生成できる床がありません。','AI');return false;}var e=K.Entities.createEnemy(s.floor,cell,K.Dungeons.get(s.dungeonId),id);e.hp=clamp(document.querySelector('[data-gm-enemy-hp]').value||e.hp,1,999);e.maxHp=Math.max(e.maxHp,e.hp);var asleep=document.querySelector('[data-gm-enemy-sleep]').checked;e.spawnSleep=asleep;e.awake=!asleep;e.effectSleep=asleep?0:e.effectSleep;e.status=e.status||{};if(document.querySelector('[data-gm-enemy-stop]').checked)e.status.bind=9999;if(document.querySelector('[data-gm-enemy-ai-off]').checked)e.aiDisabled=true;s.enemies.push(e);log(e.name+'を生成。','AI');sync();return true;}
  function targetEnemies(){var s=state();if(targetMode==='room'){var pl=p(),room=s.rooms.find(function(r){return pl.x>=r.x&&pl.x<r.x+r.w&&pl.y>=r.y&&pl.y<r.y+r.h;});return room?s.enemies.filter(function(e){return e.x>=room.x&&e.x<room.x+room.w&&e.y>=room.y&&e.y<room.y+room.h;}):[];}if(targetMode==='selected'){var id=document.querySelector('[data-gm-existing-enemy]').value;return s.enemies.filter(function(e,i){return String(i)===id;});}var c=frontCell();return s.enemies.filter(function(e){return e.x===c.x&&e.y===c.y;});}
  function applyStatus(who,type){var s=state(),targets=who==='player'?[p()]:targetEnemies();targets.forEach(function(t){t.status=t.status||{};if(type==='poison')t.status.poison=12;else if(type==='sleep'){t.status.sleep=5;t.effectSleep=5;t.spawnSleep=false;t.awake=true;}else if(type==='confuse')t.status.confuse=8;else if(type==='haste')t.status.haste=10,t.speed=2;else if(type==='slow')t.speed=.5;else if(type==='bind')t.status.bind=9999;else if(type==='powerDown')p().power=Math.max(1,p().power-1);else if(type==='hunger')p().food=Math.max(0,p().food-20);else if(type==='weaken'){var gear=p().equipment.weapon||p().equipment.shield;if(gear){gear.modifier--;gear.bonus--;}}});log('状態を付与: '+type,'状態異常');sync();}
  function clearStatus(){var s=state();[s.player].concat(s.enemies).forEach(function(t){t.status={sleep:0,confuse:0,haste:0,poison:0,bind:0};t.effectSleep=0;t.spawnSleep=false;t.awake=true;if(t.speed&&t.behaviorType)t.speed=t.behaviorType==='fast'?2:t.behaviorType==='slow'?.5:1;});log('状態異常をすべて解除。','状態異常');sync();}
  function setPlayerValues(){var pl=p();pl.level=clamp(document.querySelector('[data-gm-level]').value,1,K.Progression?K.Progression.MAX_LEVEL:99);pl.exp=clamp(document.querySelector('[data-gm-exp]').value,0,9999999);pl.hp=clamp(document.querySelector('[data-gm-hp]').value,0,9999);pl.maxHp=clamp(document.querySelector('[data-gm-maxhp]').value,1,9999);pl.food=clamp(document.querySelector('[data-gm-food]').value,0,999);pl.maxFood=clamp(document.querySelector('[data-gm-maxfood]').value,1,999);pl.power=clamp(document.querySelector('[data-gm-power]').value,1,99);pl.maxPower=clamp(document.querySelector('[data-gm-maxpower]').value,1,99);pl.gold=clamp(document.querySelector('[data-gm-gold]').value,0,999999);var d=document.querySelector('[data-gm-facing]').value.split(',');pl.facingDirection={dx:Number(d[0]),dy:Number(d[1])};if(K.Progression)K.Progression.applyLevels(pl);log('プレイヤー値を更新。','セーブ');sync();}
  function addExp(){var n=clamp(document.querySelector('[data-gm-exp-add]').value,0,999999);if(K.Progression)K.Progression.addExp(p(),n);else p().exp+=n;log(n+'経験値を追加。','セーブ');sync();}
  function changeFloor(){var s=state();s.floor=clamp(document.querySelector('[data-gm-floor]').value,1,99);s.gmSeed=document.querySelector('[data-gm-seed]').value||'';seeded(s.gmSeed,function(){K.Game.buildFloor();});state().gmMode=true;state().gmSeed=s.gmSeed;log(state().floor+'Fを生成。Seed: '+(s.gmSeed||'random'),'セーブ');sync();}
  function turnOnce(opts){var s=state(),pl=s.player,hp=pl.hp,food=pl.food,statusSnapshot=JSON.stringify(pl.status),hunger=pl.hungerClock;if(opts&&opts.enemyOnly)K.Entities.takeEnemyTurns(s);else K.Game.endTurn();if(flags.invincible||flags.enemyAttackOff)pl.hp=hp;if(flags.noHunger){pl.food=food;pl.hungerClock=hunger;}if(flags.freezeStatuses)pl.status=JSON.parse(statusSnapshot);K.Map.reveal(s);K.State.save();K.UI.draw(s);}
  function advanceTurns(n){for(var i=0;i<n;i++)turnOnce({enemyOnly:document.querySelector('[data-gm-enemy-only]').checked});log(n+'ターン進めました。','AI');sync();}
  function gmDefaults(s){s.gmMode=true;s.player.hp=s.player.maxHp;s.player.food=100;s.player.power=8;s.player.maxPower=8;s.player.gold=s.player.gold||0;s.inventory=[];s.log=['GMモードで検証を開始した。'];s.gm={flags:flags,debugLog:gmLog};}
  function visualMode(){var on=active(),badge=document.querySelector('[data-gm-badge]'),panelButton=document.querySelector('[data-gm-panel-toggle]');document.body.classList.toggle('gm-active',on);document.body.classList.toggle('gm-panel-open',on&&open);if(badge)badge.classList.toggle('hidden',!on);if(panelButton){panelButton.hidden=!on;panelButton.disabled=!on;panelButton.classList.toggle('active',on&&open);panelButton.setAttribute('aria-pressed',String(on&&open));}if(panel&&!on){open=false;panel.classList.add('hidden');document.body.classList.remove('gm-panel-open');}}
  function start(which){if(which==='gm'&&!DEBUG)return;mode=which==='gm'?'gm':'normal';saveMode();K.State.clearSave();K.Game.actions.newGame(K.Config.defaultDungeon);if(mode==='gm'){gmDefaults(state());K.State.save();log('GMモードを開始。','セーブ');sync();toggle(true);}else{state().gmMode=false;K.State.save();toggle(false);sync();}visualMode();}
  function openOnCurrentState(){if(!DEBUG)return;if(!K.State||!K.State.data)return;mode='gm';saveMode();state().gmMode=true;state().gm=state().gm||{flags:flags,debugLog:gmLog};K.State.save();log('現在の冒険をGMモードで開いた。','セーブ');visualMode();toggle(true);}
  function applyFlag(name,value){flags[name]=value;if(name==='allIdentified'&&value)state().inventory.concat(state().groundItems).forEach(K.Items.identify);if(name==='uncurse'&&value)state().inventory.concat(state().groundItems).forEach(function(i){i.cursed=false;i.curseKnown=true;});document.body.classList.toggle('gm-photo',flags.photo);document.body.classList.toggle('gm-hide-status',flags.hideStatus);document.body.classList.toggle('gm-hide-message',flags.hideMessage);document.body.classList.toggle('gm-hide-minimap',flags.hideMinimap);document.body.classList.toggle('gm-hide-controls',flags.hideControls);document.body.classList.toggle('gm-hide-arrow',flags.hideArrow);sync();}
  function renderLog(){var box=panel&&panel.querySelector('[data-gm-log]');if(!box)return;box.innerHTML=gmLog.map(function(l){return'<div><small>'+l.time+' '+l.tag+'</small>'+l.text+'</div>';}).join('');}
  function options(){var ids=visibleItemIds(),itemOptions=ids.map(function(id){var d=K.Items.definitions[id];return'<option value="'+id+'">'+categoryName(d.category)+'：'+d.trueName+'</option>';}).join(''),enemyOptions=K.EnemyCatalog.list.map(function(e){return'<option value="'+e.id+'">'+e.name+'（'+e.floorRange[0]+'-'+e.floorRange[1]+'F）</option>';}).join('');selectedItemId=selectedItemId||ids[0];selectedEnemyId=selectedEnemyId||K.EnemyCatalog.list[0].id;return{items:itemOptions,enemies:enemyOptions};}
  function renderPanel(){if(!panel||!active())return;var pl=p(),s=state(),opts=options(),existing=s.enemies.map(function(e,i){return'<option value="'+i+'">'+i+': '+e.name+' HP'+e.hp+'</option>';}).join('');panel.querySelector('[data-gm-summary]').textContent='GM / '+s.floor+'F / Seed: '+(s.gmSeed||'random')+' / 敵'+s.enemies.length+' / 道具'+s.inventory.length+'/'+C.inventoryMax;panel.querySelector('[data-gm-level]').value=pl.level;panel.querySelector('[data-gm-exp]').value=pl.exp;panel.querySelector('[data-gm-hp]').value=pl.hp;panel.querySelector('[data-gm-maxhp]').value=pl.maxHp;panel.querySelector('[data-gm-food]').value=pl.food;panel.querySelector('[data-gm-power]').value=pl.power;panel.querySelector('[data-gm-maxpower]').value=pl.maxPower;panel.querySelector('[data-gm-gold]').value=pl.gold;var itemSel=panel.querySelector('[data-gm-item]'),enemySel=panel.querySelector('[data-gm-enemy]'),existSel=panel.querySelector('[data-gm-existing-enemy]');if(itemSel.innerHTML!==opts.items)itemSel.innerHTML=opts.items;itemSel.value=selectedItemId;if(enemySel.innerHTML!==opts.enemies)enemySel.innerHTML=opts.enemies;enemySel.value=selectedEnemyId;if(existSel.innerHTML!==existing)existSel.innerHTML=existing;renderLog();}
  function panelHtml(){return'<aside id="gmPanel" class="gm-panel hidden"><div class="gm-head"><div><small>DEVELOPMENT ONLY</small><h2>GMモード</h2><p data-gm-summary></p></div><button data-gm-close>閉じる</button></div><div class="gm-grid">'+
  '<section><h3>モード</h3><button data-gm-start-normal>通常モード</button><button data-gm-start-gm>GM新規開始</button><button data-gm-rebuild>現在階を再生成</button><label>階<input data-gm-floor type="number" min="1" max="99" value="1"></label><label>Seed<input data-gm-seed placeholder="未入力ならランダム"></label><button data-gm-copy-seed>Seedコピー</button></section>'+
  '<section><h3>プレイヤー編集</h3><label>Lv<input data-gm-level type="number"></label><label>累計EXP<input data-gm-exp type="number"></label><label>EXP追加<input data-gm-exp-add type="number" value="10"></label><button data-gm-add-exp>追加</button><label>HP<input data-gm-hp type="number"></label><label>最大HP<input data-gm-maxhp type="number"></label><label>満腹<input data-gm-food type="number"></label><label>最大満腹<input data-gm-maxfood type="number" value="100"></label><label>ちから<input data-gm-power type="number"></label><label>最大ちから<input data-gm-maxpower type="number"></label><label>G<input data-gm-gold type="number"></label><label>向き<select data-gm-facing><option value="0,-1">上</option><option value="1,-1">右上</option><option value="1,0">右</option><option value="1,1">右下</option><option value="0,1">下</option><option value="-1,1">左下</option><option value="-1,0">左</option><option value="-1,-1">左上</option></select></label><button data-gm-apply-player>反映</button></section>'+
  '<section><h3>アイテム生成</h3><select data-gm-item></select><label><input data-gm-item-identified type="checkbox" checked>識別済み</label><label><input data-gm-item-cursed type="checkbox">呪い</label><label>補正<input data-gm-item-mod type="number" value="0"></label><label>杖回数<input data-gm-item-charges type="number" value="5"></label><label>矢本数<input data-gm-item-qty type="number" value="12"></label><button data-gm-item-bag>道具袋へ追加</button><button data-gm-item-foot>足元へ配置</button><button data-gm-item-front>前方へ配置</button><button data-gm-item-coord>指定座標へ配置</button><button data-gm-all-items>全アイテム追加</button></section>'+
  '<section><h3>敵スポーン</h3><select data-gm-enemy></select><label>HP<input data-gm-enemy-hp type="number" placeholder="既定"></label><label><input data-gm-enemy-sleep type="checkbox">眠っている</label><label><input data-gm-enemy-stop type="checkbox">行動停止</label><label><input data-gm-enemy-ai-off type="checkbox">AI無効</label><button data-gm-enemy-front>前方</button><button data-gm-enemy-around>周囲8マス</button><button data-gm-enemy-room>同じ部屋</button><button data-gm-enemy-coord>指定座標</button><label>対象敵<select data-gm-existing-enemy></select></label></section>'+
  '<section><h3>座標・ダンジョン</h3><label>X<input data-gm-x type="number" value="1"></label><label>Y<input data-gm-y type="number" value="1"></label><button data-gm-stairs>階段生成</button><button data-gm-trap>罠生成</button><button data-gm-clear-enemies>敵全削除</button><button data-gm-clear-items>アイテム全削除</button><button data-gm-clear-traps>罠全削除</button><button data-gm-map-all>マップ全表示</button><button data-gm-show-enemies>敵全表示</button><button data-gm-show-items>アイテム全表示</button><button data-gm-show-traps>罠全表示</button></section>'+
  '<section><h3>ターン送り</h3><label><input data-gm-enemy-only type="checkbox">敵ターンだけ</label><button data-gm-turn="1">1ターン</button><button data-gm-turn="10">10ターン</button><button data-gm-turn="100">100ターン</button></section>'+
  '<section><h3>状態異常</h3><label>対象<select data-gm-target><option value="frontEnemy">前方の敵</option><option value="selected">選択した敵</option><option value="room">同じ部屋の敵全体</option></select></label><button data-gm-player-status="poison">プレイヤー毒</button><button data-gm-player-status="sleep">プレイヤー睡眠</button><button data-gm-player-status="confuse">プレイヤー混乱</button><button data-gm-player-status="haste">プレイヤー倍速</button><button data-gm-player-status="powerDown">ちから低下</button><button data-gm-player-status="hunger">満腹度減少</button><button data-gm-player-status="weaken">装備弱化</button><button data-gm-enemy-status="sleep">敵睡眠</button><button data-gm-enemy-status="confuse">敵混乱</button><button data-gm-enemy-status="haste">敵倍速</button><button data-gm-enemy-status="slow">敵鈍足</button><button data-gm-enemy-status="bind">敵停止</button><button data-gm-clear-status>すべて解除</button></section>'+
  '<section><h3>デバッグ補助</h3>'+['log:ログ','invincible:無敵','noHunger:満腹固定','enemyStop:敵停止','enemyAIStop:敵AI停止','wallWalk:壁抜け移動','allIdentified:すべて識別済み','uncurse:呪い解除','alwaysHit:攻撃必中','enemyAttackOff:敵攻撃無効','noExp:経験値取得無効','dropAlways:ドロップ確定','dropNever:ドロップ無効','overlayVision:視界表示','overlayMove:移動表示','photo:撮影モード','hideStatus:ステータス非表示','hideMessage:ログ非表示','hideMinimap:ミニマップ非表示','hideControls:操作非表示','hideArrow:方向矢印非表示'].map(function(s){var a=s.split(':');return'<label><input data-gm-flag="'+a[0]+'" type="checkbox" '+(flags[a[0]]?'checked':'')+'>'+a[1]+'</label>';}).join('')+'</section>'+
  '<section><h3>プリセット</h3><button data-gm-preset="sleep">睡眠敵テスト</button><button data-gm-preset="blast">範囲攻撃テスト</button><button data-gm-preset="flame">火ふき草テスト</button><button data-gm-preset="pierce">貫通の矢テスト</button><button data-gm-preset="poison">毒テスト</button><button data-gm-preset="rust">装備弱化テスト</button><button data-gm-preset="gameover">ゲームオーバーテスト</button><button data-gm-preset="level">レベルアップテスト</button></section>'+
  '</div><section class="gm-log"><h3>GMデバッグログ</h3><div data-gm-log></div></section></aside>';}
  function bindPanel(){panel.addEventListener('change',function(e){var t=e.target;if(t.matches('[data-gm-item]'))selectedItemId=t.value;if(t.matches('[data-gm-enemy]'))selectedEnemyId=t.value;if(t.matches('[data-gm-target]'))targetMode=t.value;if(t.matches('[data-gm-flag]'))applyFlag(t.dataset.gmFlag,t.checked);});panel.addEventListener('click',function(e){var b=e.target.closest('button');if(!b)return;if(b.matches('[data-gm-close]'))toggle(false);else if(b.matches('[data-gm-start-normal]'))start('normal');else if(b.matches('[data-gm-start-gm]'))start('gm');else if(b.matches('[data-gm-rebuild]'))changeFloor();else if(b.matches('[data-gm-copy-seed]'))navigator.clipboard&&navigator.clipboard.writeText(state().gmSeed||'');else if(b.matches('[data-gm-apply-player]'))setPlayerValues();else if(b.matches('[data-gm-add-exp]'))addExp();else if(b.matches('[data-gm-item-bag]'))addItem('bag');else if(b.matches('[data-gm-item-foot]'))addItem('foot');else if(b.matches('[data-gm-item-front]'))addItem('front');else if(b.matches('[data-gm-item-coord]'))addItem('coord');else if(b.matches('[data-gm-all-items]'))addAllItems();else if(b.matches('[data-gm-enemy-front]'))spawnEnemy('front');else if(b.matches('[data-gm-enemy-around]'))spawnEnemy('around');else if(b.matches('[data-gm-enemy-room]'))spawnEnemy('room');else if(b.matches('[data-gm-enemy-coord]'))spawnEnemy('coord');else if(b.matches('[data-gm-stairs]')){state().stairs=frontCell();sync();}else if(b.matches('[data-gm-trap]')){var c=frontCell();if(K.Map.walkable(state(),c.x,c.y))state().traps.push(K.Traps.createRandom(state(),c));sync();}else if(b.matches('[data-gm-clear-enemies]')){state().enemies=[];sync();}else if(b.matches('[data-gm-clear-items]')){state().groundItems=[];sync();}else if(b.matches('[data-gm-clear-traps]')){state().traps=[];sync();}else if(b.matches('[data-gm-map-all]')){allVisible(state());sync();}else if(b.matches('[data-gm-show-enemies]')){state().vision.enemies=true;sync();}else if(b.matches('[data-gm-show-items]')){state().vision.items=true;sync();}else if(b.matches('[data-gm-show-traps]')){state().vision.traps=true;state().traps.forEach(function(t){t.revealed=true;});sync();}else if(b.matches('[data-gm-turn]'))advanceTurns(Number(b.dataset.gmTurn));else if(b.matches('[data-gm-player-status]'))applyStatus('player',b.dataset.gmPlayerStatus);else if(b.matches('[data-gm-enemy-status]'))applyStatus('enemy',b.dataset.gmEnemyStatus);else if(b.matches('[data-gm-clear-status]'))clearStatus();else if(b.matches('[data-gm-preset]'))preset(b.dataset.gmPreset);});}
  function preset(id){flags.log=true;if(id==='sleep'){spawnEnemy('front');var e=state().enemies[state().enemies.length-1];if(e){e.spawnSleep=true;e.awake=false;}log('睡眠敵テストを準備。','AI');}else if(id==='blast'){addItem('bag','blastScroll');for(var i=0;i<4;i++)spawnEnemy('room');}else if(id==='flame'){addItem('bag','flameHerb');spawnEnemy('front');}else if(id==='pierce'){addItem('bag','pierceArrow');for(var n=1;n<=3;n++){var c=frontCell(n+1);if(clearOccupation(state(),c.x,c.y))state().enemies.push(K.Entities.createEnemy(state().floor,c,K.Dungeons.get(state().dungeonId),'dewMote'));}}else if(id==='poison'){selectedEnemyId='bileToad';spawnEnemy('front');addItem('bag','antidoteRing');}else if(id==='rust'){addItem('bag','mistSaber');addItem('bag','barkShield');selectedEnemyId='rustMaw';spawnEnemy('front');}else if(id==='gameover'){p().hp=1;spawnEnemy('front');}else if(id==='level'){if(K.Progression){var next=K.Progression.EXP_TABLE[p().level]||p().exp+1;p().exp=Math.max(0,next-1);}var c2=frontCell();if(clearOccupation(state(),c2.x,c2.y)){var enemy=K.Entities.createEnemy(state().floor,c2,K.Dungeons.get(state().dungeonId),'dewMote');enemy.hp=1;state().enemies.push(enemy);}}sync();}
  function toggle(force){if(!active()){visualMode();return;}open=force===undefined?!open:!!force;if(panel)panel.classList.toggle('hidden',!open);visualMode();if(open)renderPanel();}
  var oldSave=K.State.save,oldLoad=K.State.load,oldClear=K.State.clearSave;
  K.State.save=function(){try{localStorage.setItem(saveKey(),JSON.stringify(this.data));}catch(e){}};
  K.State.load=function(){var ok=false;try{var keys=mode==='gm'?[C.gmSaveKey].concat(C.legacyGmSaveKeys||[]):[C.normalSaveKey].concat(C.legacyNormalSaveKeys||[],C.saveKey,C.legacySaveKeys||[]),raw=null;for(var i=0;!raw&&i<keys.length;i++)raw=localStorage.getItem(keys[i]);if(!raw)return false;var legacy=localStorage.getItem(C.saveKey);localStorage.setItem(C.saveKey,raw);ok=oldLoad.call(this);if(legacy===null)localStorage.removeItem(C.saveKey);else localStorage.setItem(C.saveKey,legacy);if(ok){this.data.gmMode=mode==='gm';this.save();}}catch(e){}return ok;};
  K.State.clearSave=function(){try{localStorage.removeItem(saveKey());}catch(e){}};
  var oldTurns=K.Entities.takeEnemyTurns;K.Entities.takeEnemyTurns=function(s){if(active()&&(flags.enemyStop||flags.enemyAIStop)){log('敵ターンを停止。','AI');return;}var before=s.player.hp,result=oldTurns.call(this,s);if(active()&&(flags.invincible||flags.enemyAttackOff))s.player.hp=before;return result;};
  var oldAct=K.Entities.enemyAct;K.Entities.enemyAct=function(s,e){if(active()){if(e.aiDisabled){log(e.name+'：AI停止中','AI');return;}log(e.name+'：行動判断開始','AI');}var result=oldAct.call(this,s,e);if(active())log(e.name+'：行動結果 '+(result||'通常処理'),'AI');return result;};
  var oldReward=K.Entities.rewardDefeat;K.Entities.rewardDefeat=function(s,e,award){var oldDrop=e.dropRate,oldExp=s.player.exp,oldLevel=s.player.level;if(active()&&flags.dropNever)e.dropRate=0;if(active()&&flags.dropAlways)e.dropRate=1;var result=oldReward.call(this,s,e,active()&&flags.noExp?false:award);if(active()&&flags.noExp){s.player.exp=oldExp;s.player.level=oldLevel;}e.dropRate=oldDrop;return result;};
  var oldCanStep=K.Map.canStep;K.Map.canStep=function(s,x,y,dx,dy){if(active()&&flags.wallWalk)return x>=0&&y>=0&&x<C.width&&y<C.height&&!s.enemies.some(function(e){return e.x===x&&e.y===y;});return oldCanStep.call(this,s,x,y,dx,dy);};
  var oldHasEffect=K.Items.hasEffect;K.Items.hasEffect=function(s,effect){if(active()&&flags.noHunger&&effect==='noHunger')return true;return oldHasEffect.call(this,s,effect);};
  var oldDraw=K.UI.draw;K.UI.draw=function(s){oldDraw.call(this,s);visualMode();if(!active())return;var canvas=document.querySelector('#game'),ctx=canvas&&canvas.getContext('2d'),tile=C.tile,pl=s.player;if(!ctx)return;ctx.save();if(flags.overlayVision){ctx.fillStyle='rgba(80,190,255,.14)';for(var y=pl.y-C.visionRadius;y<=pl.y+C.visionRadius;y++)for(var x=pl.x-C.visionRadius;x<=pl.x+C.visionRadius;x++)if(x>=0&&y>=0&&x<C.width&&y<C.height&&Math.hypot(x-pl.x,y-pl.y)<=C.visionRadius)ctx.fillRect(x*tile,y*tile,tile,tile);s.enemies.forEach(function(e){ctx.strokeStyle='rgba(255,70,70,.35)';ctx.strokeRect((e.x-1)*tile,(e.y-1)*tile,tile*3,tile*3);});}if(flags.overlayMove){for(var yy=0;yy<C.height;yy++)for(var xx=0;xx<C.width;xx++){ctx.fillStyle=K.Map.walkable(s,xx,yy)?'rgba(80,255,120,.08)':'rgba(255,80,80,.12)';ctx.fillRect(xx*tile,yy*tile,tile,tile);}}ctx.restore();};
  function init(){if(!DEBUG)return;var header=document.querySelector('header');if(header){var box=document.createElement('div');box.className='gm-mode-launch';box.innerHTML='<button data-gm-panel-toggle hidden disabled aria-pressed="false">GMパネル</button>';header.appendChild(box);box.querySelector('[data-gm-panel-toggle]').addEventListener('click',function(){toggle();});}document.body.insertAdjacentHTML('beforeend',panelHtml());panel=document.querySelector('#gmPanel');bindPanel();addEventListener('keydown',function(e){var editing=e.target&&e.target.closest&&e.target.closest('input,textarea,select,[contenteditable="true"]'),inPanel=e.target&&e.target.closest&&e.target.closest('#gmPanel');if(open&&active()&&!inPanel){if(e.key==='F12'){e.preventDefault();toggle(false);return;}e.preventDefault();e.stopImmediatePropagation();return;}if(editing){e.stopPropagation();return;}if(e.key==='F12'&&active()){e.preventDefault();toggle();}},true);if(mode==='gm'&&K.State.data)K.State.data.gmMode=true;setTimeout(function(){visualMode();if(active())toggle(true);},0);}
  K.Mode={isDebug:function(){return DEBUG;},current:function(){return mode;},set:function(next){mode=next==='gm'&&DEBUG?'gm':'normal';saveMode();},saveKey:saveKey};
  K.GM={active:active,flags:flags,log:log,start:start,openCurrent:openOnCurrentState,toggle:toggle,isOpen:function(){return open&&active();},spawnEnemy:spawnEnemy,addItem:addItem,advanceTurns:advanceTurns,seeded:seeded,gmDefaults:gmDefaults,logs:function(){return gmLog.slice();}};
  addEventListener('DOMContentLoaded',init);
})(window.Kiri=window.Kiri||{});
