(function(K){'use strict';
  function remove(state,item){var i=state.inventory.indexOf(item);if(i>=0)state.inventory.splice(i,1);}
  function pointFree(state,x,y){return K.Map.walkable(state,x,y)&&!state.enemies.some(function(e){return e.x===x&&e.y===y;});}
  function ray(state,max){var p=state.player,f=p.facingDirection||{dx:0,dy:1},cells=[];for(var n=1;n<=max;n++){var x=p.x+f.dx*n,y=p.y+f.dy*n;if(!K.Map.walkable(state,x,y))break;cells.push({x:x,y:y});}return cells;}
  function enemyAt(state,p){return state.enemies.find(function(e){return e.x===p.x&&e.y===p.y;});}
  function killDead(state){state.enemies=state.enemies.filter(function(e){return e.hp>0;});}
  function visibleName(item){return K.Items.name(item).replace(/（[^）]*）$/,'').replace(/×\d+$/,'');}
  function defeatedText(enemy){return enemy.hp<=0?' '+enemy.name+'を倒した。':'';}
  function applyDamageToEnemy(state,enemy,damage,sourceName){var amount=Math.max(0,Math.floor(damage||0)),text=enemy.name+'に'+amount+'のダメージを与えた。',reward=null;enemy.hp-=amount;if(enemy.hp<=0){reward=K.Entities.rewardDefeat(state,enemy,true);text+=enemy.name+'を倒した。'+reward.exp+'ポイントの経験値を得た。';(reward.levels||[]).forEach(function(level){text+=' レベルが'+level+'に上がった！';});if(reward.drop)text+=' '+reward.drop;}var outcome={sourceName:sourceName||'',enemy:enemy,damage:amount,defeated:!!reward,reward:reward,text:text};enemy.lastDamageOutcome=outcome;return outcome;}
  K.CombatDamage={applyDamageToEnemy:applyDamageToEnemy};
  function effectText(item,enemy){var e=item.effect;if(e==='sleep')return enemy.name+'を眠らせた。';if(e==='slow')return enemy.name+'を鈍足にした。';if(e==='confuse')return enemy.name+'を混乱させた。';if(e==='blind')return enemy.name+'を目つぶし状態にした。';if(e==='warp')return enemy.name+'を別の場所へ飛ばした。';if(e==='poison')return enemy.name+'を毒状態にした。';if(e==='haste')return enemy.name+'を倍速にした。';if(e==='change')return enemy.name+'の姿を変えた。';if(e==='hpOne'||e==='sacrifice')return enemy.name+'のHPを1にした。';if(e==='heal25'||e==='heal100')return enemy.name+'のHPを回復させた。';return enemy.name+'に効果を与えた。';}
  function wallBeyond(state,cells,max){if(cells.length>=max)return false;var p=cells.length?cells[cells.length-1]:state.player,f=state.player.facingDirection||{dx:0,dy:1};return!K.Map.walkable(state,p.x+f.dx,p.y+f.dy);}
  function dropFree(state,x,y){return K.Map.walkable(state,x,y)&&!(state.player.x===x&&state.player.y===y)&&!state.enemies.some(function(e){return e.x===x&&e.y===y;})&&!state.groundItems.some(function(item){return item.x===x&&item.y===y;});}
  function safeDropCell(state,planned){if(dropFree(state,planned.x,planned.y))return planned;var candidates=[];for(var dy=-1;dy<=1;dy++)for(var dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;var x=planned.x+dx,y=planned.y+dy;if(dropFree(state,x,y))candidates.push({x:x,y:y});}K.Util.shuffle(candidates);return candidates[0]||planned;}
  function warpEntity(state,entity){for(var i=0;i<100;i++){var p=K.Map.freeCell(state,0);if(p){entity.x=p.x;entity.y=p.y;return true;}}return false;}
  function flameDamage(){return 65+K.Util.rand(11);}
  function thrownFlameDamage(){return 35+K.Util.rand(6);}
  function burnItemsAt(state,x,y){
    var burned=[];
    state.groundItems=(state.groundItems||[]).filter(function(item){
      if(item.x===x&&item.y===y){burned.push(K.Items.name(item));return false;}
      return true;
    });
    return burned;
  }
  function applyFlameDamageToEnemy(state,enemy,damage,sourceName){
    var x=enemy.x,y=enemy.y,outcome=applyDamageToEnemy(state,enemy,damage,sourceName);
    if(outcome.defeated){
      var burned=burnItemsAt(state,x,y);
      if(burned.length)outcome.text+=' '+burned.join('、')+'は炎で燃え尽きた。';
    }
    return outcome;
  }
  function revealAllTraps(state){state.vision.traps=true;(state.traps||[]).forEach(function(t){t.revealed=true;t.identified=true;});}
  function applyHerbPlayer(state,item){
    var p=state.player,e=item.effect,outcomes=[],beforeHp=p.hp,beforeMax=p.maxHp,full=p.hp>=p.maxHp;
    p.status=p.status||{};
    p.food=Math.min(100,p.food+(e==='flame'?1:5));
    if(e==='heal25'||e==='heal100'){
      if(full){var gain=e==='heal100'?2:1;p.maxHp+=gain;p.hp+=gain;}
      else p.hp=Math.min(p.maxHp,p.hp+(e==='heal100'?100:25));
      outcomes.push({kind:'self',text:full?'最大HPが'+(p.maxHp-beforeMax)+'増えた。':'HPが'+Math.max(0,p.hp-beforeHp)+'回復した。'});
    }else if(e==='powerMend'){var bp=p.power;p.power=p.maxPower;outcomes.push({kind:'self',text:p.power>bp?'ちからが最大まで回復した。':'ちからは下がっていなかった。'});}
    else if(e==='powerUp'){p.maxPower++;p.power++;outcomes.push({kind:'self',text:'ちからが1上がった。'});}
    else if(e==='level'){var hpGain=3;p.level++;p.maxHp+=hpGain;p.hp=Math.min(p.maxHp,(p.hp||0)+hpGain);outcomes.push({kind:'self',text:'レベルが'+p.level+'に上がった。'});}
    else if(e==='haste'){p.status.haste=10;outcomes.push({kind:'self',text:'体が軽くなった。'});}
    else if(e==='sight'){revealAllTraps(state);outcomes.push({kind:'self',text:'この階の罠の位置と種類が見えるようになった。'});}
    else if(e==='poison'){if(!K.Items.hasEffect(state,'poisonGuard')){p.hp=Math.max(1,p.hp-5);p.power=Math.max(1,p.power-1);outcomes.push({kind:'self',text:'毒でHPとちからが下がった。'});}else outcomes.push({kind:'self',text:'毒よけが毒を防いだ。'});}
    else if(e==='confuse'){p.status.confuse=8;outcomes.push({kind:'self',text:'方向感覚が乱れた。'});}
    else if(e==='blind'){p.status.blind=8;outcomes.push({kind:'self',text:'目の前が見えにくくなった。'});}
    else if(e==='invisible'){p.status.invisible=8;outcomes.push({kind:'self',text:'姿が透明になった。'});}
    else if(e==='sleep'){if(!K.Items.hasEffect(state,'sleepGuard')){p.status.sleep=5;outcomes.push({kind:'self',text:'眠気に包まれた。'});}else outcomes.push({kind:'self',text:'眠らずの指輪が眠りを防いだ。'});}
    else if(e==='warp'){warpEntity(state,p);outcomes.push({kind:'self',text:'別の場所へ飛ばされた。'});}
    else if(e==='flame'){var cells=ray(state,10),target=null;for(var i=0;i<cells.length&&!target;i++)target=enemyAt(state,cells[i]);if(target)outcomes.push(applyFlameDamageToEnemy(state,target,flameDamage(),item.trueName));else outcomes.push({kind:'self',text:'炎は空を切った。'});}
    return outcomes;
  }
  function applyHerbEnemy(state,item,enemy){var e=item.effect,outcome=null;enemy.status=enemy.status||{sleep:0,confuse:0,poison:0,bind:0,blind:0};if(e==='heal25'||e==='heal100')enemy.hp=Math.min(enemy.maxHp,enemy.hp+(e==='heal100'?100:25));else if(e==='powerMend')enemy.power+=1;else if(e==='powerUp')enemy.power+=2;else if(e==='level'){enemy.hp+=8;enemy.maxHp+=8;enemy.power+=2;}else if(e==='haste')enemy.speed=2;else if(e==='poison'){enemy.hp-=5;enemy.power=Math.max(1,enemy.power-1);enemy.status.poison=12;}else if(e==='confuse')enemy.status.confuse=8;else if(e==='blind')enemy.status.blind=8;else if(e==='sleep'){enemy.effectSleep=5;enemy.status.sleep=5;}else if(e==='warp')warpEntity(state,enemy);else if(e==='flame')outcome=applyFlameDamageToEnemy(state,enemy,thrownFlameDamage(),item.trueName);else if(e==='sight')enemy.status.revealed=true;killDead(state);return outcome;}
  function applyStaffEnemy(state,item,target){var e=item.effect;target.status=target.status||{sleep:0,confuse:0,poison:0,bind:0,blind:0};if(e==='thunder')target.hp-=22;else if(e==='slow')target.speed=.5;else if(e==='sleep'){target.effectSleep=6;target.status.sleep=6;}else if(e==='confuse')target.status.confuse=10;else if(e==='blind')target.status.blind=10;else if(e==='warp')warpEntity(state,target);else if(e==='change'){target.hp=8+state.floor*2;target.maxHp=target.hp;target.power=2+Math.floor(state.floor/2);}else if(e==='haste')target.speed=2;else if(e==='hpOne'||e==='sacrifice')target.hp=1;killDead(state);}
  function playerEffectText(item){var e=item.effect;if(e==='thunder')return'雷撃がはね返り、自分に当たった。';if(e==='slow')return'体が重くなった。';if(e==='sleep')return'眠気が自分を包んだ。';if(e==='confuse')return'方向感覚が乱れた。';if(e==='blind')return'目の前が見えにくくなった。';if(e==='warp')return'はね返った力で別の場所へ飛ばされた。';if(e==='change')return'水晶が揺らめいたが、姿は変わらなかった。';if(e==='haste')return'体が軽くなった。';if(e==='sacrifice')return'命を削る力が自分へ返ってきた。';if(e==='invisible')return'姿が透明になった。';return'杖の力が自分へ返ってきた。';}
  function herbMessages(item,outcomes){var messages=[item.trueName+'を飲んだ。'];(outcomes||[]).forEach(function(o){if(o&&o.text)messages.push(o.text);});return messages;}
  function applyStaffPlayer(state,item){var p=state.player,e=item.effect;p.status=p.status||{};if(e==='thunder')p.hp=Math.max(0,p.hp-22);else if(e==='slow')p.status.slow=6;else if(e==='sleep'){if(!K.Items.hasEffect(state,'sleepGuard'))p.status.sleep=6;}else if(e==='confuse')p.status.confuse=10;else if(e==='blind')p.status.blind=10;else if(e==='warp')warpEntity(state,p);else if(e==='haste')p.status.haste=10;else if(e==='sacrifice')p.hp=Math.max(1,p.hp-Math.max(1,Math.floor(p.hp/2)));else if(e==='invisible')p.status.invisible=10;return playerEffectText(item);}
  function thrownDamage(item){if(item.category==='arrow')return Math.max(1,item.basePower||3);if(item.category==='weapon')return Math.max(1,Math.min(4,item.basePower||item.bonus||2));if(item.category==='shield')return 2;return 1;}
  function equip(state,item){var slot=item.category,current=state.player.equipment[slot];if(current&&current.cursed)return{success:false,message:'呪いが絡みつき、'+K.Items.name(current)+'を外せない。'};if(current)current.equipped=false;state.player.equipment[slot]=item;item.equipped=true;item.curseKnown=true;return{success:true,message:K.Items.name(item)+'を装備した。'};}
  function unequip(state,item){if(item.cursed)return{success:false,message:'呪いが絡みつき、外せない。'};state.player.equipment[item.category]=null;item.equipped=false;return{success:true,message:K.Items.name(item)+'を外した。'};}
  function throwItem(state,item){var cells=ray(state,10),last={x:state.player.x,y:state.player.y},name=visibleName(item),wall=wallBeyond(state,cells,10);remove(state,item);for(var i=0;i<cells.length;i++){last=cells[i];var enemy=enemyAt(state,last);if(enemy){var before=enemy.hp,outcome=null;if(item.category==='herb')outcome=applyHerbEnemy(state,item,enemy);else if(item.category==='staff')applyStaffEnemy(state,item,enemy);else{enemy.hp-=thrownDamage(item);killDead(state);}var damage=outcome?outcome.damage:Math.max(0,before-enemy.hp),message=name+'を投げ、'+(outcome?outcome.text:(damage?enemy.name+'に'+damage+'ダメージを与えた。':effectText(item,enemy)));if(!outcome)message+=defeatedText(enemy);return{success:true,message:message,damage:damage,targetName:enemy.name,defeated:enemy.hp<=0};}}var landing=safeDropCell(state,last);item.x=landing.x;item.y=landing.y;item.equipped=false;state.groundItems.push(item);return{success:true,message:name+'を投げ、'+name+(wall?'は壁に当たって床に落ちた。':'は外れて床に落ちた。'),damage:0,missed:true,wall:wall,landing:landing};}
  function place(state,item){if(state.groundItems.some(function(i){return i.x===state.player.x&&i.y===state.player.y;}))return{success:false,message:'足元にはすでに道具がある。'};remove(state,item);item.x=state.player.x;item.y=state.player.y;item.equipped=false;state.groundItems.push(item);return{success:true,message:K.Items.name(item)+'を足元に置いた。'};}
  function shoot(state,item){var pierce=item.effect==='pierce',cells=ray(state,10),last={x:state.player.x,y:state.player.y},hits=[],name=visibleName(item);item.quantity--;for(var i=0;i<cells.length;i++){last=cells[i];var enemy=enemyAt(state,last);if(enemy){var power=K.Items.arrowAttackPower?K.Items.arrowAttackPower(state,item):item.basePower,damage=Math.max(1,power+K.Util.rand(3)-1-(enemy.defense||0));hits.push(applyDamageToEnemy(state,enemy,damage,name));if(!pierce)break;}}if(item.quantity<=0){remove(state,item);if(state.player.equipment.arrow===item)state.player.equipment.arrow=null;}if(!hits.length){var arrow=K.Items.create(item.id,last.x,last.y,state.dungeonId);arrow.quantity=1;arrow.equipped=false;state.groundItems.push(arrow);}var messages=hits.length?[name+'を撃った。'].concat(hits.map(function(hit){return hit.text;})):[name+'を撃ったが、外れた。'];return{success:true,message:messages.join('\n'),messages:messages,hits:hits,missed:!hits.length};}
  function staff(state,item){var initialName=visibleName(item);if(item.charges<=0)return{success:true,message:initialName+'を振ったが、効果は起きなかった。'};item.charges--;K.Items.identify(item);var name=visibleName(item);if(item.effect==='invisible'){state.player.status=state.player.status||{};state.player.status.invisible=10;return{success:true,message:name+'を振り、姿が透明になった。'};}var cells=ray(state,10),target=null;for(var i=0;i<cells.length;i++){target=enemyAt(state,cells[i]);if(target)break;}if(!target&&K.CrystalWalls){var crystal=K.CrystalWalls.firstInRay(state,10);if(crystal){var selfText=applyStaffPlayer(state,item);return{success:true,message:name+'を振った。水晶壁が杖の力をはね返した。 '+selfText,reflected:true};}}if(!target)return{success:true,message:name+'を振ったが、外れた。',missed:true};var before=target.hp,e=item.effect,outcome=null;if(e==='thunder')outcome=applyDamageToEnemy(state,target,22,name);else if(e==='slow')target.speed=.5;else if(e==='sleep'){target.effectSleep=6;target.status.sleep=6;}else if(e==='confuse')target.status.confuse=10;else if(e==='blind')target.status.blind=10;else if(e==='warp')warpEntity(state,target);else if(e==='change'){target.hp=8+state.floor*2;target.maxHp=target.hp;target.power=2+Math.floor(state.floor/2);target.kind=K.Util.rand(2);}else if(e==='haste')target.speed=2;else if(e==='sacrifice'){var cost=Math.max(1,Math.floor(state.player.hp/2));state.player.hp-=cost;outcome=applyDamageToEnemy(state,target,cost*2,name);}if(outcome){var messages=[name+'を振った。',outcome.text];return{success:true,message:messages.join(' '),messages:messages,damage:outcome.damage,targetName:target.name,defeated:outcome.defeated};}var damage=Math.max(0,before-target.hp),message=name+'を振り、'+effectText(item,target);return{success:true,message:message,damage:damage,targetName:target.name,defeated:false};}
  function read(state,item){var p=state.player,e=item.effect,msg=item.trueName+'を読んだ。';if(e==='escape')return{success:true,consume:true,endRun:true,message:'帰路の光が迷宮の外へ導いた。'};if(e==='weaponUp'){var w=p.equipment.weapon;if(w){w.modifier++;w.bonus++;w.cursed=false;w.curseKnown=true;}else msg='強める武器がなかった。';}else if(e==='shieldUp'){var s=p.equipment.shield;if(s){s.modifier++;s.bonus++;s.cursed=false;s.curseKnown=true;}else msg='強める盾がなかった。';}else if(e==='uncurse'){['weapon','shield','ring'].forEach(function(k){var q=p.equipment[k];if(q){q.cursed=false;q.curseKnown=true;}});}else if(e==='identify'){var unknown=state.inventory.find(function(q){return!q.identified||!q.chargesKnown;});if(unknown)K.Items.identify(unknown);else msg='正体不明の道具はなかった。';}else if(e==='map'){state.vision.mapAll=true;state.vision.items=true;revealAllTraps(state);K.Visibility.update(state);msg='道標の紙片を読んだ。\n階全体が明るくなり、地形と罠と道具の位置が明らかになった。';}else if(e==='traps'){revealAllTraps(state);}else if(e==='items')state.vision.items=true;else if(e==='enemies'){state.vision.enemies=true;msg='敵見えの紙片を読んだ。\nこの階にいる敵の気配が地図に浮かび上がった。';}else if(e==='blast'){var room=state.rooms.find(function(r){return p.x>=r.x&&p.x<r.x+r.w&&p.y>=r.y&&p.y<r.y+r.h;});state.enemies.forEach(function(q){if(room?q.x>=room.x&&q.x<room.x+room.w&&q.y>=room.y&&q.y<room.y+room.h:K.Util.distance(p,q)<=1)q.hp-=20;});killDead(state);}else if(e==='food'){var target=state.inventory.find(function(q){return q!==item&&q.category!=='food';});if(target){var index=state.inventory.indexOf(target);state.inventory[index]=K.Items.create('bigBread',undefined,undefined,state.dungeonId);}else msg='食料へ変える道具がなかった。';}else if(e==='charge'){var wand=state.inventory.find(function(q){return q.category==='staff';});if(wand){wand.charges+=1+K.Util.rand(3);wand.chargesKnown=true;}else msg='力を継ぐ杖がなかった。';}return{success:true,consume:true,message:msg};}
  K.ItemActions={actionsFor:function(item){if(item.equipped)return[{id:'unequip',label:'外す'}];var first={food:['eat','食べる'],herb:['drink','飲む'],scroll:['read','読む'],staff:['wave','振る'],weapon:['equip','装備'],shield:['equip','装備'],ring:['equip','装備'],arrow:['shoot','撃つ']}[item.category],list=[];if(first)list.push({id:first[0],label:first[1]});if(item.category==='arrow')list.push({id:'equip',label:'装備'},{id:'place',label:'置く'});else if(item.category==='treasure')list.push({id:'place',label:'置く'});else list.push({id:'throw',label:'投げる'},{id:'place',label:'置く'});return list;},perform:function(action,state,item){if(action==='equip')return equip(state,item);if(action==='unequip')return unequip(state,item);if(action==='throw')return throwItem(state,item);if(action==='place')return place(state,item);if(action==='shoot'){if(state.player&&state.player.status&&state.player.status.sleep>0)return{success:false,message:'深い眠りで矢を撃てない。'};return shoot(state,item);}if(action==='wave')return staff(state,item);if(action==='read'){var result=read(state,item);if(result.consume)remove(state,item);return result;}if(action==='eat'){if(item.id==='nutBread')state.player.food=Math.min(100,state.player.food+50);else if(item.id==='bigBread')state.player.food=100;else{state.player.food=100;state.player.hp=Math.max(1,state.player.hp-5);state.player.power=Math.max(1,state.player.power-1);}remove(state,item);return{success:true,message:K.Items.name(item)+'を食べた。'};}if(action==='drink'){var outcomes=applyHerbPlayer(state,item),messages=herbMessages(item,outcomes);K.Items.identify(item);remove(state,item);return{success:true,message:messages.join('\n'),messages:messages};}return{success:false,message:'その使い方はできない。'};},applyHerbEnemy:applyHerbEnemy,warpEntity:warpEntity};
  K.ItemActions.shootEquipped=function(state){var arrow=state.player.equipment.arrow,held=(state.inventory||[]).find(function(item){return item.category==='arrow'&&item.equipped;});if(held&&held!==arrow){state.player.equipment.arrow=held;arrow=held;}if(!arrow||arrow.quantity<=0)return{success:false,message:'矢を装備していない。'};return shoot(state,arrow);};
  var damagePerform=K.ItemActions.perform;
  K.ItemActions.perform=function(action,state,item){
    if(action==='read'&&item.effect==='blast'){
      var p=state.player,room=state.rooms.find(function(r){return p.x>=r.x&&p.x<r.x+r.w&&p.y>=r.y&&p.y<r.y+r.h;});
      var targets=state.enemies.filter(function(enemy){return room?enemy.x>=room.x&&enemy.x<room.x+room.w&&enemy.y>=room.y&&enemy.y<room.y+room.h:K.Util.distance(p,enemy)<=1;});
      var outcomes=targets.map(function(enemy){return applyDamageToEnemy(state,enemy,20,item.trueName);});
      remove(state,item);var messages=[item.trueName+'を使用した。'].concat(outcomes.map(function(outcome){return outcome.text;}));
      return{success:true,message:messages.join('\n'),messages:messages,outcomes:outcomes};
    }
    var tracked=(action==='drink'&&item.effect==='flame')?state.enemies.slice():[],result=damagePerform.apply(this,arguments);
    if(tracked.length&&result&&result.success){var hits=tracked.map(function(enemy){return enemy.lastDamageOutcome;}).filter(function(outcome){return outcome&&outcome.sourceName===item.trueName;});if(hits.length){result.messages=[item.trueName+'を使用した。'].concat(hits.map(function(outcome){return outcome.text;}));result.message=result.messages.join('\n');}}
    if(result&&result.messages)result.message=result.messages.join('\n');
    return result;
  };
})(window.Kiri=window.Kiri||{});


