(function(K){
  'use strict';
  var oldDraw=K.UI.draw;
  function floorTile(state,x,y){return state.map[y]&&state.map[y][x]===1;}
  function roomTile(state,x,y){return!!K.Visibility.roomAt(state,x,y);}
  function drawPlayer(ctx,p){var t=K.Config.tile,cx=p.x*t+10,cy=p.y*t+10,f=p.facingDirection||{dx:0,dy:1};ctx.fillStyle='#e4b84f';ctx.beginPath();ctx.arc(cx,cy-1,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#5c785c';ctx.fillRect(cx-5,cy+3,10,5);ctx.strokeStyle='#fff2a8';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+f.dx*9,cy+f.dy*9);ctx.stroke();}
  function drawTheme(ctx,state){var name=K.Themes.forFloor(state.floor).name;ctx.font='12px system-ui, sans-serif';ctx.textAlign='left';ctx.textBaseline='top';var w=Math.ceil(ctx.measureText(name).width)+12;ctx.fillStyle='rgba(8,10,8,.58)';ctx.fillRect(5,5,w,21);ctx.fillStyle='rgba(242,234,197,.82)';ctx.fillText(name,11,9);}
  function redrawMain(state){var canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),theme=K.Themes.forFloor(state.floor),t=K.Config.tile;ctx.fillStyle='#030403';ctx.fillRect(0,0,canvas.width,canvas.height);for(var y=0;y<K.Config.height;y++)for(var x=0;x<K.Config.width;x++){if(!K.Visibility.isMapped(state,x,y))continue;var visible=K.Visibility.isVisible(state,x,y),floor=floorTile(state,x,y);ctx.globalAlpha=visible?1:.32;ctx.fillStyle=floor?(roomTile(state,x,y)?theme.floor:theme.corridor):theme.wall;ctx.fillRect(x*t,y*t,t,t);if(floor){ctx.strokeStyle=theme.grid;ctx.strokeRect(x*t+.5,y*t+.5,t-1,t-1);}}ctx.globalAlpha=1;if(state.stairs&&K.Visibility.isMapped(state,state.stairs.x,state.stairs.y)){var sx=state.stairs.x*t,sy=state.stairs.y*t;K.Stairs[state.stairs.type==='up'?'drawUp':'drawDown'](ctx,sx,sy);}
    state.traps.forEach(function(trap){if(trap.revealed&&K.Visibility.isVisible(state,trap.x,trap.y)){if(K.TrapRenderer)K.TrapRenderer.draw(ctx,trap,trap.x*t,trap.y*t,t);else{ctx.strokeStyle='#bd79d0';ctx.beginPath();ctx.arc(trap.x*t+10,trap.y*t+10,6,0,Math.PI*2);ctx.stroke();}}});
    state.groundItems.forEach(function(item){if(K.Visibility.isVisible(state,item.x,item.y)&&!(state.player.x===item.x&&state.player.y===item.y))K.ItemIcons.draw(ctx,item.category,item.x*t+1,item.y*t+1,18);});
    state.enemies.forEach(function(enemy){if(K.Visibility.isVisible(state,enemy.x,enemy.y))K.EnemyRenderer.draw(ctx,enemy,t);});drawPlayer(ctx,state.player);drawTheme(ctx,state);
  }
  function redrawMini(state){var canvas=document.querySelector('#minimap'),ctx=canvas.getContext('2d'),s=5;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='rgba(2,3,2,.84)';ctx.fillRect(0,0,canvas.width,canvas.height);for(var y=0;y<K.Config.height;y++)for(var x=0;x<K.Config.width;x++){if(!K.Visibility.isMapped(state,x,y))continue;var visible=K.Visibility.isVisible(state,x,y),floor=floorTile(state,x,y);ctx.fillStyle=floor?(visible?'#8a917d':'#3a4035'):(visible?'#42483d':'#20241f');ctx.fillRect(x*s,y*s,s,s);}if(state.stairs&&K.Visibility.isMapped(state,state.stairs.x,state.stairs.y)){ctx.fillStyle='#fff0a3';ctx.fillRect(state.stairs.x*s+1,state.stairs.y*s+1,3,3);}state.groundItems.forEach(function(item){if(K.Visibility.shouldShowItemOnMap?K.Visibility.shouldShowItemOnMap(state,item):K.Visibility.isVisible(state,item.x,item.y)){ctx.fillStyle='#62d7e8';ctx.fillRect(item.x*s+1,item.y*s+1,3,3);}});state.traps.forEach(function(trap){if(K.Visibility.shouldShowTrapOnMap?K.Visibility.shouldShowTrapOnMap(state,trap):(trap.revealed&&K.Visibility.isMapped(state,trap.x,trap.y))){if(K.TrapRenderer)K.TrapRenderer.drawMini(ctx,trap,trap.x*s+2.5,trap.y*s+2.5,s);else{ctx.fillStyle='#c36ad9';ctx.fillRect(trap.x*s+1,trap.y*s+1,3,3);}}});state.enemies.forEach(function(enemy){if(K.Visibility.shouldShowEnemyOnMap?K.Visibility.shouldShowEnemyOnMap(state,enemy):K.Visibility.isVisible(state,enemy.x,enemy.y)){ctx.fillStyle='#ee5148';ctx.fillRect(enemy.x*s+1,enemy.y*s+1,3,3);}});ctx.fillStyle='#fff176';ctx.fillRect(state.player.x*s,state.player.y*s,5,5);}
  K.UI.draw=function(state){oldDraw.call(K.UI,state);redrawMain(state);redrawMini(state);};K.UI.redrawVisibility=redrawMain;K.UI.redrawMinimap=redrawMini;
})(window.Kiri=window.Kiri||{});
