'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');global.window=global;global.Kiri={};const store={};global.localStorage={getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v,removeItem:k=>delete store[k]};global.addEventListener=()=>{};function load(f){vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});}
['config','spawns','dungeons','themes','enemy-catalog','items','inventory','item-icons','state','stage8-state','stage10-state','map','visibility','stage15-state','combat-rules','entities','enemy-renderer','sprites','animation','item-actions','stage10-items','balance','traps','stairs'].forEach(n=>load('js/'+n+'.js'));
function arena(){const s=Kiri.State.reset('normalDungeon');s.map=Array.from({length:24},()=>Array(32).fill(1));s.rooms=[{x:0,y:0,w:32,h:24}];s.player.x=16;s.player.y=12;s.player.hp=100;s.player.maxHp=100;s.player.facingDirection={dx:1,dy:0};s.stairs={x:18,y:12,type:'down'};s.enemies=[];s.groundItems=[];s.inventory=[];s.traps=[];s.seen={};s.mapped={};s.visible={};s.spawnPolicy={nextSpawnTurn:999,maxEnemies:10,naturalSpawnInterval:30};Kiri.Visibility.update(s);return s;}

// Player sprite supports every requested state and preserves left/right orientation.
['idle','walk','attack','arrow','staff','damage','death'].forEach(type=>{Kiri.Animation.player(type,500,{dx:type==='walk'?-1:1,dy:0});let frame=Kiri.Animation.playerFrame(performance.now());assert.equal(frame.type,type);});Kiri.Animation.player('walk',500,{dx:-1,dy:0});assert.equal(Kiri.Animation.playerFrame(performance.now()).facing,'left');Kiri.Animation.player('walk',500,{dx:1,dy:0});assert.equal(Kiri.Animation.playerFrame(performance.now()).facing,'right');
const transforms=[];function spriteContext(){return{fillRect(){},beginPath(){},arc(){},fill(){},stroke(){},moveTo(){},lineTo(){},save(){},restore(){},translate(x,y){transforms.push([x,y]);},scale(x,y){transforms.push(['scale',x,y]);},set fillStyle(v){},set globalAlpha(v){},set strokeStyle(v){},set lineWidth(v){}};}let ctx=spriteContext();Kiri.Sprites.drawPlayer(ctx,0,0,{type:'idle',progress:0},0,'left');Kiri.Sprites.drawPlayer(ctx,0,0,{type:'idle',progress:0},400,'right');assert(transforms.some(v=>v[0]==='scale'&&v[1]===-1));assert(transforms.some(v=>v[0]==='scale'&&v[1]===1));

// All catalog enemies map to a sprite family; silhouettes are not color-only variants.
const families=Kiri.EnemyCatalog.list.map(e=>Kiri.Sprites.familyFor(e));assert.equal(families.length,25);assert(new Set(families).size>=12);Kiri.EnemyCatalog.list.forEach(def=>{ctx=spriteContext();assert.doesNotThrow(()=>Kiri.Sprites.drawEnemy(ctx,Object.assign({x:0,y:0},def),0,0,{type:'idle',progress:0},300));});

// Zoomed camera is 20x15 tiles and keeps the player near the center.
const mainRecords=[],miniRecords=[];function canvasContext(records){return{fillStyle:'',strokeStyle:'',font:'',textAlign:'',globalAlpha:1,lineWidth:1,fillRect(x,y,w,h){records.push({kind:'fill',color:this.fillStyle,x,y,w,h});},strokeRect(x,y,w,h){records.push({kind:'stroke',color:this.strokeStyle,x,y,w,h});},clearRect(){},beginPath(){},arc(x,y,r){records.push({kind:'arc',color:this.fillStyle,x,y,r});},fill(){},stroke(){},moveTo(){},lineTo(){},rect(){},ellipse(){},closePath(){},save(){},restore(){},translate(){},scale(){},measureText:()=>({width:30}),fillText(){}};}const canvases={game:{width:640,height:480,getContext:()=>canvasContext(mainRecords)},minimap:{width:160,height:120,getContext:()=>canvasContext(miniRecords)}};global.document={querySelector:q=>canvases[q.slice(1)]||null};Kiri.UI={draw:()=>{}};load('js/stage16-ui.js');let s=arena(),cam=Kiri.UI.stage16Camera(s);assert.deepStrictEqual(cam,{x:6,y:5});assert.equal(20*32,640);assert.equal(15*32,480);

// Minimap colors/shapes: yellow player, cyan item, red enemy, cyan hollow stair square.
let item=Kiri.Items.create('moonHerb',17,12,s.dungeonId);s.groundItems=[item];let enemy=Kiri.Entities.createEnemy(1,{x:15,y:12},Kiri.Dungeons.get(s.dungeonId),'chaser');s.enemies=[enemy];Kiri.UI.renderStage16Minimap(s);assert(miniRecords.some(r=>r.kind==='arc'&&r.color==='#ffd51f'));assert(miniRecords.some(r=>r.kind==='arc'&&r.color==='#43d5ec'));assert(miniRecords.some(r=>r.kind==='arc'&&r.color==='#ed382f'));assert(miniRecords.some(r=>r.kind==='stroke'&&r.color==='#42d9e8'));assert(!miniRecords.some(r=>r.kind==='fill'&&r.color==='#42d9e8'));

// Action hooks select walking, attack, arrow, staff, damage and death animations.
let delayed=false;global.setTimeout=fn=>{delayed=true;return 1;};Kiri.UI={draw:()=>{},showStairs:()=>{},closeStairs:()=>{},closeItemMenu:()=>{},showGameOver:()=>{},showEscape:()=>{},hideOverlay:()=>{},closeStatus:()=>{},toggleStatus:()=>{},showSuspend:()=>{},closeSuspend:()=>{}};Kiri.Input={resetModes:()=>{}};Kiri.Audio={setTheme:()=>{}};load('js/game.js');load('js/stage16-controller.js');s=arena();Kiri.Game.actions.move(1,0);assert.equal(Kiri.Animation.playerFrame(performance.now()).type,'walk');Kiri.Game.actions.attack();assert.equal(Kiri.Animation.playerFrame(performance.now()).type,'attack');Kiri.Game.actions.shootArrow();assert.equal(Kiri.Animation.playerFrame(performance.now()).type,'arrow');item=Kiri.Items.create('thunderStaff',undefined,undefined,s.dungeonId);s.inventory=[item];Kiri.ItemActions.perform('wave',s,item);assert.equal(Kiri.Animation.playerFrame(performance.now()).type,'staff');enemy=Kiri.Entities.createEnemy(1,{x:s.player.x+1,y:s.player.y},Kiri.Dungeons.get(s.dungeonId),'chaser');s.enemies=[enemy];Kiri.Entities.enemyAct(s,enemy);assert.equal(Kiri.Animation.playerFrame(performance.now()).type,'damage');Kiri.UI.showGameOver(s);assert.equal(Kiri.Animation.playerFrame(performance.now()).type,'death');assert(delayed);

// Responsive layout docks the minimap outside the main canvas.
const html=fs.readFileSync('index.html','utf8'),css=fs.readFileSync('style.css','utf8');assert(html.includes('class="map-layout"'));assert(html.includes('class="minimap-dock"'));assert(html.indexOf('id="minimap"')>html.indexOf('</div>'));assert(html.includes('js/sprites.js'));assert(html.includes('js/animation.js'));assert(css.includes('left:calc(100% + 10px)'));assert(css.includes('@media(max-width:869px)'));
console.log('stage 16 smoke: zoom camera, animated sprites, enemy families and detached minimap passed');
