'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');global.window=global;global.Kiri={};global.localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};global.addEventListener=()=>{};let clock=100;global.performance={now:()=>clock};
function load(f){vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});}
['config','spawns','dungeons','themes','enemy-catalog','items','inventory','state','map','visibility','combat-rules','entities','sprites','animation','item-actions','stage10-items','balance','traps'].forEach(n=>load('js/'+n+'.js'));
function arena(){const s=Kiri.State.reset('normalDungeon');s.map=Array.from({length:24},()=>Array(32).fill(1));s.rooms=[{x:0,y:0,w:32,h:24,id:1}];s.player.x=2;s.player.y=2;s.player.facingDirection={dx:1,dy:0};s.enemies=[];s.groundItems=[];s.traps=[];s.inventory=[];s.spawnPolicy={maxEnemies:10};return s;}

// A wall collision relocates a thrown item away from an occupied landing tile.
const random=Math.random;Math.random=()=>0;let s=arena();s.map[2][5]=0;let occupied=Kiri.Items.create('moonHerb',4,2,s.dungeonId),thrown=Kiri.Items.create('mistSaber',undefined,undefined,s.dungeonId);s.groundItems=[occupied];s.inventory=[thrown];let result=Kiri.ItemActions.perform('throw',s,thrown);assert(result.wall);assert.notDeepStrictEqual([thrown.x,thrown.y],[4,2]);assert(Kiri.Map.walkable(s,thrown.x,thrown.y));assert(!s.enemies.some(e=>e.x===thrown.x&&e.y===thrown.y));assert(!(s.player.x===thrown.x&&s.player.y===thrown.y));assert.equal(s.groundItems.filter(i=>i.x===thrown.x&&i.y===thrown.y).length,1);assert(Math.max(Math.abs(thrown.x-4),Math.abs(thrown.y-2))<=1);

// With no valid neighboring tile, the item is retained rather than deleted.
s=arena();s.map[2][5]=0;occupied=Kiri.Items.create('moonHerb',4,2,s.dungeonId);let blocker=Kiri.Items.create('nutBread',3,2,s.dungeonId);thrown=Kiri.Items.create('mistSaber',undefined,undefined,s.dungeonId);s.groundItems=[occupied,blocker];s.inventory=[thrown];for(let y=1;y<=3;y++)for(let x=3;x<=5;x++)if(!(x===3&&y===2)&&!(x===4&&y===2)&&!(x===5&&y===2))s.map[y][x]=0;result=Kiri.ItemActions.perform('throw',s,thrown);assert(s.groundItems.includes(thrown));assert.equal(thrown.x,4);assert.equal(thrown.y,2);Math.random=random;

// Sleeping actors use a fixed body frame/time; damage remains animated and waking restores motion.
let recorded=null,recordedPlayer=null,texts=[];Kiri.Sprites={drawEnemy:(ctx,enemy,x,y,frame,time)=>{recorded={frame:frame,time:time};},drawPlayer:(ctx,x,y,frame,time)=>{recordedPlayer={frame:frame,time:time};}};load('js/stage27-sleep-visuals.js');s=arena();s.player.status.sleep=5;Kiri.Animation.player('walk',220,{fromX:1,fromY:2,toX:2,toY:2,dx:1,dy:0});let frame=Kiri.Animation.playerFrame(150);assert.equal(frame.type,'sleep');assert.equal(frame.offsetX,0);Kiri.Sprites.drawPlayer({save(){},restore(){},fillText(t){texts.push(t);},set fillStyle(v){},set font(v){},set textAlign(v){},set textBaseline(v){}},0,0,frame,900,'E',s.player);assert.equal(recordedPlayer.frame.type,'sleep');assert.equal(recordedPlayer.time,0);assert(texts.includes('z'));s.player.status.sleep=0;
let enemy=Kiri.Entities.createEnemy(1,{x:6,y:5},Kiri.Dungeons.get(s.dungeonId),'driftMoth');enemy.spawnSleep=true;enemy.awake=false;Kiri.Animation.enemy(enemy,'walk',220,{fromX:5,fromY:5,toX:6,toY:5,dx:1,dy:0});frame=Kiri.Animation.enemyFrame(enemy,150);assert.equal(frame.type,'sleep');assert.equal(frame.offsetX,0);Kiri.Sprites.drawEnemy({},enemy,0,0,frame,900);assert.equal(recorded.frame.type,'sleep');assert.equal(recorded.time,-(enemy.x+enemy.y)*260);Kiri.Animation.enemy(enemy,'damage',220);frame=Kiri.Animation.enemyFrame(enemy,150);assert.equal(frame.type,'damage');enemy.spawnSleep=false;enemy.awake=true;Kiri.Animation.enemy(enemy,'walk',220,{fromX:5,fromY:5,toX:6,toY:5,dx:1,dy:0});frame=Kiri.Animation.enemyFrame(enemy,150);assert.equal(frame.type,'walk');assert.notEqual(frame.offsetX,0);

const html=fs.readFileSync('index.html','utf8');assert(html.includes('js/stage27-sleep-visuals.js'));
console.log('stage 27 smoke: safe thrown-item landing and frozen sleep animation passed');
