'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');global.window=global;global.Kiri={};global.localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};global.addEventListener=()=>{};let scheduled=null;global.setTimeout=fn=>{scheduled=fn;return 1;};global.clearTimeout=()=>{scheduled=null;};
function load(f){vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});}
['config','spawns','dungeons','themes','enemy-catalog','items','inventory','item-icons','item-details','state','stage8-state','stage10-state','stage15-state','map','visibility','combat-rules','entities','enemy-renderer','sprites','animation','item-actions','stage10-items','balance','traps','stairs','stage23-combat','stage22-rewards'].forEach(n=>load('js/'+n+'.js'));
Kiri.UI={draw:()=>{},showItemMenu:()=>{},closeItemMenu:()=>{},showItemDetails:()=>{},hideTooltip:()=>{},showConfirm:()=>{},closeConfirm:()=>{},setInventorySelection:()=>{},showStairs:()=>{},closeStairs:()=>{},showGameOver:()=>{},showEscape:()=>{},hideOverlay:()=>{},closeStatus:()=>{},toggleStatus:()=>{},showSuspend:()=>{},closeSuspend:()=>{}};Kiri.Input={resetModes:()=>{}};Kiri.Audio={setTheme:()=>{}};load('js/game.js');load('js/stage7-controller.js');load('js/stage17-controller.js');load('js/stage24-controller.js');
function arena(){const s=Kiri.State.reset('normalDungeon');s.map=Array.from({length:24},()=>Array(32).fill(1));s.rooms=[{x:0,y:0,w:32,h:24,id:1}];s.player.x=2;s.player.y=2;s.player.hp=100;s.player.maxHp=100;s.player.facingDirection={dx:1,dy:0};s.stairs={x:30,y:22};s.enemies=[];s.groundItems=[];s.traps=[];s.inventory=[];s.spawnPolicy={nextSpawnTurn:999,maxEnemies:10,naturalSpawnInterval:30};Kiri.State.data=s;return s;}

// Equipped arrows merge even at the 20-slot limit; overflow remains on the floor.
let s=arena(),stack=Kiri.Items.create('reedArrow',undefined,undefined,s.dungeonId);stack.quantity=90;stack.equipped=true;s.player.equipment.arrow=stack;s.inventory=[stack];for(let i=0;i<19;i++)s.inventory.push(Kiri.Items.create('moonHerb',undefined,undefined,s.dungeonId));let floorArrow=Kiri.Items.create('reedArrow',3,2,s.dungeonId);floorArrow.quantity=15;s.groundItems=[floorArrow];Kiri.Game.actions.move(1,0);assert.equal(s.inventory.length,20);assert.equal(stack.quantity,99);assert.equal(floorArrow.quantity,6);assert(s.groundItems.includes(floorArrow));assert.strictEqual(s.player.equipment.arrow,stack);

// Non-arrow items remain separate slots.
s=arena();let herbA=Kiri.Items.create('moonHerb',undefined,undefined,s.dungeonId),herbB=Kiri.Items.create('moonHerb',3,2,s.dungeonId);s.inventory=[herbA];s.groundItems=[herbB];Kiri.Game.actions.move(1,0);assert.equal(s.inventory.filter(i=>i.id==='moonHerb').length,2);

// Projectile actions leave HP, logs and enemy turns untouched until animation completion.
s=arena();stack=Kiri.Items.create('reedArrow',undefined,undefined,s.dungeonId);stack.quantity=3;stack.equipped=true;s.player.equipment.arrow=stack;s.inventory=[stack];let enemy=Kiri.Entities.createEnemy(1,{x:5,y:2},Kiri.Dungeons.get(s.dungeonId),'dewMote');enemy.hp=20;enemy.maxHp=20;enemy.spawnSleep=false;enemy.dropRate=0;s.enemies=[enemy];let hp=enemy.hp,turn=s.turn;assert(Kiri.Game.actions.shootArrow());assert(Kiri.ActionSequence.isBusy());assert.equal(enemy.hp,hp);assert.equal(s.turn,turn);assert.equal(Kiri.Game.actions.move(1,0),false);assert(scheduled);let complete=scheduled;scheduled=null;complete();assert(enemy.hp<hp);assert.equal(s.turn,turn+1);assert(!Kiri.ActionSequence.isBusy());assert.equal(stack.quantity,2);

// Wand and thrown-item paths use the same deferred turn gate.
s=arena();let wand=Kiri.Items.create('thunderStaff',undefined,undefined,s.dungeonId);s.inventory=[wand];enemy=Kiri.Entities.createEnemy(1,{x:5,y:2},Kiri.Dungeons.get(s.dungeonId),'dewMote');enemy.hp=40;enemy.maxHp=40;enemy.spawnSleep=false;enemy.dropRate=0;s.enemies=[enemy];Kiri.Game.actions.openItem(0);Kiri.Game.actions.itemAction('wave');assert.equal(enemy.hp,40);complete=scheduled;scheduled=null;complete();assert.equal(enemy.hp,18);assert.equal(s.turn,1);
s=arena();let food=Kiri.Items.create('nutBread',undefined,undefined,s.dungeonId);s.inventory=[food];enemy=Kiri.Entities.createEnemy(1,{x:5,y:2},Kiri.Dungeons.get(s.dungeonId),'dewMote');enemy.hp=20;enemy.maxHp=20;enemy.spawnSleep=false;enemy.dropRate=0;s.enemies=[enemy];Kiri.Game.actions.openItem(0);Kiri.Game.actions.itemAction('throw');assert.equal(enemy.hp,20);complete=scheduled;scheduled=null;complete();assert.equal(enemy.hp,19);assert.equal(s.turn,1);

const html=fs.readFileSync('index.html','utf8');assert(html.includes('js/stage24-controller.js'));
console.log('stage 24 smoke: capped arrow merging and animation-gated projectile turns passed');
