'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');global.window=global;global.Kiri={};global.localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};global.addEventListener=()=>{};function load(f){vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});}
['config','spawns','dungeons','themes','enemy-catalog','items','inventory','item-icons','state','map','visibility','combat-rules','entities','enemy-renderer','sprites','stage17-sprites','animation','item-actions','stage10-items','balance','traps','stairs'].forEach(n=>load('js/'+n+'.js'));
function arena(){const s=Kiri.State.reset('normalDungeon');s.map=Array.from({length:24},()=>Array(32).fill(1));s.rooms=[];s.player.x=2;s.player.y=2;s.player.facingDirection={dx:1,dy:1};s.stairs={x:10,y:10,type:'down'};s.enemies=[];s.groundItems=[];s.traps=[];s.inventory=[];s.mapped={};for(let y=0;y<24;y++)for(let x=0;x<32;x++)s.mapped[Kiri.Util.key(x,y)]=1;s.seen=s.mapped;s.visible={[Kiri.Util.key(2,2)]:1};return s;}

// Explored item/stair memories remain, while unseen enemies stay hidden.
const records=[];const miniCtx={fillStyle:'',strokeStyle:'',lineWidth:1,clearRect(){},fillRect(x,y,w,h){records.push({kind:'fill',color:this.fillStyle,x,y,w,h});},strokeRect(x,y,w,h){records.push({kind:'stroke',color:this.strokeStyle,x,y,w,h});},beginPath(){},arc(x,y,r){records.push({kind:'arc',color:this.fillStyle,x,y,r});},fill(){},stroke(){}};const mainCtx={fillRect(){},strokeRect(){},beginPath(){},arc(){},fill(){},stroke(){},moveTo(){},lineTo(){},save(){},restore(){},translate(){},scale(){},measureText:()=>({width:20}),fillText(){}};global.document={querySelector:q=>q==='#minimap'?{width:160,height:120,getContext:()=>miniCtx}:q==='#game'?{width:640,height:480,getContext:()=>mainCtx}:null};Kiri.UI={draw:()=>{}};load('js/stage16-ui.js');let s=arena(),item=Kiri.Items.create('moonHerb',8,8,s.dungeonId);s.groundItems=[item];let enemy=Kiri.Entities.createEnemy(1,{x:9,y:9},Kiri.Dungeons.get(s.dungeonId),'chaser');s.enemies=[enemy];Kiri.UI.renderStage16Minimap(s);assert(records.some(r=>r.kind==='arc'&&r.color==='#43d5ec'));assert(records.some(r=>r.kind==='stroke'&&r.color==='#42d9e8'));assert(!records.some(r=>r.kind==='arc'&&r.color==='#ed382f'));s.visible[Kiri.Util.key(9,9)]=1;records.length=0;Kiri.UI.renderStage16Minimap(s);assert(records.some(r=>r.kind==='arc'&&r.color==='#ed382f'));

// All 25 enemies receive a unique geometry signature, not just a new color.
function spriteCtx(){const ops=[];return{ops:ops,fillRect(x,y,w,h){ops.push(['r',Math.round(x),Math.round(y),w,h]);},beginPath(){},arc(x,y,r){ops.push(['a',Math.round(x),Math.round(y),Math.round(r)]);},fill(){},stroke(){},moveTo(){},lineTo(){},rect(){},ellipse(){},closePath(){},save(){},restore(){},translate(){},scale(){},set fillStyle(v){},set strokeStyle(v){},set globalAlpha(v){},set lineWidth(v){}};}const signatures=Kiri.EnemyCatalog.list.map(def=>{const c=spriteCtx();Kiri.Sprites.drawEnemy(c,Object.assign({x:0,y:0,spriteId:def.id},def),0,0,{type:'idle',progress:0},360);return JSON.stringify(c.ops);});assert.equal(new Set(signatures).size,25);

// Arrow, wand and thrown-item projectiles traverse diagonal cells and expose impact frames.
s=arena();enemy=Kiri.Entities.createEnemy(1,{x:5,y:5},Kiri.Dungeons.get(s.dungeonId),'chaser');s.enemies=[enemy];let t=performance.now();Kiri.Animation.clearProjectiles();Kiri.Animation.launch(s,'arrow',Kiri.Items.create('reedArrow',0,0,s.dungeonId));let early=Kiri.Animation.projectileFrames(t+25)[0],later=Kiri.Animation.projectileFrames(t+105)[0],impact=Kiri.Animation.projectileFrames(t+160)[0];assert(early&&later&&later.x>early.x&&later.y>early.y);assert.equal(later.dx,1);assert.equal(later.dy,1);assert(impact&&impact.impact>0&&impact.hit);
Kiri.Animation.clearProjectiles();t=performance.now();Kiri.Animation.launch(s,'wand',Kiri.Items.create('thunderStaff',0,0,s.dungeonId));assert.equal(Kiri.Animation.projectileFrames(t+20)[0].kind,'wand');Kiri.Animation.clearProjectiles();t=performance.now();Kiri.Animation.launch(s,'throw',Kiri.Items.create('nutBread',0,0,s.dungeonId));let thrown=Kiri.Animation.projectileFrames(t+20)[0];assert.equal(thrown.kind,'throw');assert.equal(thrown.category,'food');
s=arena();s.map[4][4]=0;Kiri.Animation.clearProjectiles();t=performance.now();Kiri.Animation.launch(s,'arrow',Kiri.Items.create('reedArrow',0,0,s.dungeonId));let wall=Kiri.Animation.projectileFrames(t+100)[0];assert(wall&&wall.wall&&wall.impact>0);

// Gameplay hooks launch visuals without changing the underlying item result.
const launches=[],realLaunch=Kiri.Animation.launch;Kiri.Animation.launch=function(state,kind,item){launches.push(kind);};Kiri.Game={actions:{shootArrow:()=>true}};s=arena();let equipped=Kiri.Items.create('reedArrow',0,0,s.dungeonId);s.player.equipment.arrow=equipped;Kiri.State.data=s;load('js/stage17-controller.js');Kiri.Game.actions.shootArrow();let wand=Kiri.Items.create('thunderStaff',0,0,s.dungeonId);s.inventory=[wand];Kiri.ItemActions.perform('wave',s,wand);let food=Kiri.Items.create('nutBread',0,0,s.dungeonId);s.inventory=[food];Kiri.ItemActions.perform('throw',s,food);assert.deepStrictEqual(launches,['arrow','wand','throw']);Kiri.Animation.launch=realLaunch;

// Rendering layer draws projectiles and responsive phone rules cover portrait/landscape.
const pctx={fillStyle:'',strokeStyle:'',lineWidth:1,save(){},restore(){},translate(){},rotate(){},fillRect(){this.drawn=true;},beginPath(){},arc(){},fill(){this.drawn=true;},stroke(){this.drawn=true;}};global.document={querySelector:q=>q==='#game'?{width:640,height:480,getContext:()=>pctx}:null};Kiri.UI={draw:()=>{},renderAnimationFrame:()=>{},stage16Camera:()=>({x:0,y:0})};load('js/stage17-ui.js');Kiri.Animation.clearProjectiles();s=arena();Kiri.Animation.launch(s,'wand',Kiri.Items.create('thunderStaff',0,0,s.dungeonId));Kiri.UI.drawProjectiles(s,performance.now()+30);assert(pctx.drawn);
const html=fs.readFileSync('index.html','utf8'),css=fs.readFileSync('style.css','utf8');assert(html.includes('js/stage17-sprites.js'));assert(html.includes('js/stage17-ui.js'));assert(html.includes('js/stage17-controller.js'));assert(css.includes('@media(max-width:600px)'));assert(css.includes('(orientation:landscape)'));
console.log('stage 17 smoke: map memory, 25 unique sprites, projectiles and responsive sizing passed');
