'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');global.window=global;global.Kiri={};global.localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};global.addEventListener=()=>{};let clock=100;global.performance={now:()=>clock};
function load(f){vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});}
['config','spawns','dungeons','themes','enemy-catalog','items','inventory','item-icons','state','map','visibility','combat-rules','entities','enemy-renderer','sprites','animation','item-actions','stage10-items','balance','traps','stairs'].forEach(n=>load('js/'+n+'.js'));
function arena(){const s=Kiri.State.reset('normalDungeon');s.map=Array.from({length:24},()=>Array(32).fill(1));s.rooms=[];s.player.x=2;s.player.y=2;s.player.hp=100;s.player.maxHp=100;s.player.facingDirection={dx:1,dy:0};s.stairs={x:30,y:22};s.enemies=[];s.groundItems=[];s.traps=[];s.inventory=[];s.visible={};s.mapped={};s.seen=s.mapped;s.spawnPolicy={nextSpawnTurn:999,maxEnemies:10,naturalSpawnInterval:30};Kiri.Visibility.update(s);return s;}

Kiri.Animation.player('walk',200,{dx:1,dy:1,fromX:2,fromY:2,toX:3,toY:3});let frame=Kiri.Animation.playerFrame(100);assert.equal(frame.offsetX,-1);assert.equal(frame.offsetY,-1);frame=Kiri.Animation.playerFrame(200);assert.equal(frame.offsetX,-.5);assert.equal(frame.offsetY,-.5);frame=Kiri.Animation.playerFrame(300);assert.equal(frame.type,'idle');assert.equal(frame.offsetX,0);

let s=arena(),scroll=Kiri.Items.create('mapScroll',undefined,undefined,s.dungeonId),enemy=Kiri.Entities.createEnemy(1,{x:15,y:15},Kiri.Dungeons.get(s.dungeonId),'chaser');s.inventory=[scroll];s.groundItems=[Kiri.Items.create('moonHerb',20,20,s.dungeonId)];s.traps=[{x:18,y:18,id:'mistNeedle',revealed:false}];s.enemies=[enemy];Kiri.ItemActions.perform('read',s,scroll);assert.equal(Object.keys(s.mapped).length,32*24);assert.equal(Object.keys(s.visible).length,32*24);assert(s.traps[0].revealed);assert(Kiri.Visibility.isVisible(s,20,20));assert(!Kiri.Visibility.isEntityVisible(s,enemy.x,enemy.y));assert.equal(s.vision.enemies,false);

Kiri.UI={draw:()=>{},showStairs:()=>{},closeStairs:()=>{},closeItemMenu:()=>{},showGameOver:()=>{},showEscape:()=>{},hideOverlay:()=>{},closeStatus:()=>{},toggleStatus:()=>{},showSuspend:()=>{},closeSuspend:()=>{}};Kiri.Input={resetModes:()=>{}};Kiri.Audio={setTheme:()=>{}};load('js/game.js');load('js/stage16-controller.js');s=arena();s.rooms=[{x:0,y:0,w:32,h:24,id:1}];enemy=Kiri.Entities.createEnemy(1,{x:3,y:2},Kiri.Dungeons.get(s.dungeonId),'fast');enemy.spawnSleep=true;enemy.awake=false;enemy.speed=2;s.enemies=[enemy];Kiri.State.data=s;const random=Math.random;Math.random=()=>0;let hp=s.player.hp;Kiri.Game.endTurn();assert.equal(s.player.hp,hp);assert.equal(enemy.wokeOnTurn,s.turn);assert(s.log[0].includes(enemy.name+'は目を覚ました。'));Kiri.Game.endTurn();assert(s.player.hp<hp);Math.random=random;

console.log('stage 20 smoke: interpolated walking, map-reveal visibility and wake-only turns passed');
