'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');global.window=global;global.Kiri={};const store={};global.localStorage={getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v,removeItem:k=>delete store[k]};global.addEventListener=()=>{};function load(f){vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});}
['config','spawns','dungeons','themes','enemy-catalog','items','inventory','item-icons','state','stage8-state','stage10-state','map','visibility','stage15-state','combat-rules','entities','item-actions','stage10-items','balance','traps'].forEach(n=>load('js/'+n+'.js'));
function arena(room){const s=Kiri.State.reset('normalDungeon');s.map=Array.from({length:24},()=>Array(32).fill(1));s.rooms=room?[{x:4,y:4,w:7,h:6}]:[];s.player.x=2;s.player.y=2;s.player.hp=100;s.player.maxHp=100;s.stairs={x:20,y:20,type:'down'};s.enemies=[];s.groundItems=[];s.inventory=[];s.traps=[];s.seen={};s.mapped={};s.visible={};s.spawnPolicy={nextSpawnTurn:999,maxEnemies:10,naturalSpawnInterval:30};Kiri.Visibility.update(s);return s;}
Kiri.UI={draw:()=>{},showStairs:()=>{},closeStairs:()=>{},closeItemMenu:()=>{},showGameOver:()=>{},showEscape:()=>{},hideOverlay:()=>{},closeStatus:()=>{},toggleStatus:()=>{},showSuspend:()=>{},closeSuspend:()=>{}};Kiri.Input={resetModes:()=>{}};Kiri.Audio={setTheme:()=>{}};load('js/game.js');

// Auto pickup below capacity; full bags leave the item and explicit pickup costs no turn on failure.
let s=arena(false),item=Kiri.Items.create('moonHerb',3,2,s.dungeonId);s.groundItems=[item];Kiri.Game.actions.move(1,0);assert(s.inventory.includes(item));assert.equal(s.groundItems.length,0);
s=arena(false);s.inventory=Array.from({length:20},()=>Kiri.Items.create('nutBread',undefined,undefined,s.dungeonId));item=Kiri.Items.create('moonHerb',3,2,s.dungeonId);s.groundItems=[item];Kiri.Game.actions.move(1,0);assert.equal(s.inventory.length,20);assert(s.groundItems.includes(item));let turn=s.turn;assert.equal(Kiri.Game.actions.pickup(),false);assert.equal(s.turn,turn);assert(s.log[0].includes('いっぱいです'));s.inventory.pop();assert(Kiri.Game.actions.pickup());assert.equal(s.turn,turn+1);assert(s.inventory.includes(item));

// Corridor sight is the surrounding 3x3; entering a room maps and lights the complete room plus its edge walls.
s=arena(false);Kiri.Visibility.update(s);assert.equal(Object.keys(s.visible).length,9);assert(Kiri.Visibility.isVisible(s,1,1));assert(!Kiri.Visibility.isVisible(s,4,2));
s=arena(true);s.player.x=5;s.player.y=5;Kiri.Visibility.update(s);assert(Kiri.Visibility.isVisible(s,10,9));assert(Kiri.Visibility.isMapped(s,3,3));assert(!Kiri.Visibility.isMapped(s,20,20));let mappedCount=Object.keys(s.mapped).length;s.player.x=2;s.player.y=2;Kiri.Visibility.update(s);assert(Object.keys(s.mapped).length>=mappedCount);assert(!Kiri.Visibility.isVisible(s,10,9));

// Enemy sight respects rooms, corridor range and blocking walls.
s=arena(false);let enemy={x:8,y:2};assert(Kiri.Visibility.enemyCanSee(s,enemy,s.player));s.map[2][5]=0;assert(!Kiri.Visibility.enemyCanSee(s,enemy,s.player));s=arena(true);s.player.x=5;s.player.y=5;enemy={x:9,y:8};assert(Kiri.Visibility.enemyCanSee(s,enemy,s.player));

// Spawn sleep is independent from timed item sleep and trends downward by depth.
const random=Math.random;Math.random=()=>0;s=arena(false);enemy=Kiri.Entities.createEnemy(1,{x:4,y:2},Kiri.Dungeons.get(s.dungeonId));assert(enemy.spawnSleep&&!enemy.awake);Math.random=()=>.99;let deep=Kiri.Entities.createEnemy(30,{x:8,y:2},Kiri.Dungeons.get(s.dungeonId));assert(!deep.spawnSleep&&deep.awake);
Math.random=()=>0;enemy.spawnSleep=true;enemy.awake=false;enemy.x=3;enemy.y=2;s.enemies=[enemy];Kiri.Entities.enemyAct(s,enemy);assert(!enemy.spawnSleep&&enemy.awake);
s.turn++;enemy.effectSleep=3;enemy.status.sleep=3;enemy.spawnSleep=false;enemy.awake=true;let pos=[enemy.x,enemy.y];Kiri.Entities.enemyAct(s,enemy);assert.equal(enemy.effectSleep,2);assert.deepStrictEqual([enemy.x,enemy.y],pos);Math.random=random;

// Minimap uses red enemy dots only for current sight and normal rendering still delegates to EnemyRenderer.
const records=[];function context(){return{clearRect(){},fillRect(x,y,w,h){records.push({color:this.fillStyle,x,y,w,h});},strokeRect(){},beginPath(){},arc(){},fill(){},stroke(){},moveTo(){},lineTo(){},measureText:()=>({width:20}),save(){},restore(){},translate(){},scale(){},rect(){},ellipse(){},closePath(){},set globalAlpha(v){},set font(v){},set textAlign(v){},set textBaseline(v){},set lineWidth(v){},fillText(){}};}const mainCtx=context(),miniCtx=context(),canvases={game:{width:640,height:480,getContext:()=>mainCtx},minimap:{width:160,height:120,getContext:()=>miniCtx}};global.document={querySelector:q=>canvases[q.slice(1)]||null};let normalDraws=0;Kiri.EnemyRenderer={draw:()=>normalDraws++};Kiri.Stairs={drawDown:()=>{},drawUp:()=>{}};Kiri.UI={draw:()=>{}};load('js/stage15-ui.js');s=arena(false);enemy=Kiri.Entities.createEnemy(1,{x:3,y:2},Kiri.Dungeons.get(s.dungeonId),'chaser');let hidden=Kiri.Entities.createEnemy(1,{x:10,y:10},Kiri.Dungeons.get(s.dungeonId),'chaser');s.enemies=[enemy,hidden];Kiri.UI.draw(s);assert.equal(normalDraws,1);assert(records.some(r=>r.color==='#ee5148'));assert.equal(records.filter(r=>r.color==='#ee5148').length,1);

// Legacy saves gain mapped/visible and split sleep fields.
const legacy=Kiri.State.fresh();legacy.enemies=[{x:4,y:4,hp:5,maxHp:5,power:2,awake:false,status:{sleep:2}}];store[Kiri.Config.saveKey]=JSON.stringify(legacy);assert(Kiri.State.load());assert(Kiri.State.data.mapped&&Kiri.State.data.visible);enemy=Kiri.State.data.enemies[0];assert.equal(enemy.spawnSleep,true);assert.equal(enemy.effectSleep,2);assert(enemy.spriteId);
const html=fs.readFileSync('index.html','utf8'),css=fs.readFileSync('style.css','utf8');assert(html.includes('id="minimap"'));assert(html.includes('js/visibility.js'));assert(html.includes('js/stage15-ui.js'));assert(css.includes('#minimap'));
console.log('stage 15 smoke: pickup capacity, mapping/sight, spawn sleep, minimap and migration passed');
