'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');global.window=global;global.Kiri={};const store={};global.localStorage={getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v,removeItem:k=>delete store[k]};global.addEventListener=()=>{};function load(f){vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});}
['config','spawns','dungeons','themes','enemy-catalog','items','state','stage8-state','stage10-state','map','visibility','combat-rules','entities','item-actions','stage10-items','balance','traps','stage33-projectile-rules','stage38-combat-gold-vitals'].forEach(n=>load('js/'+n+'.js'));
function arena(id='mysteryDungeon'){const s=Kiri.State.reset(id);s.map=Array.from({length:24},()=>Array(32).fill(1));s.rooms=[{x:0,y:0,w:32,h:24}];s.player.x=2;s.player.y=2;s.player.hp=50;s.player.maxHp=50;s.stairs={x:30,y:22,type:'down'};s.enemies=[];s.groundItems=[];s.inventory=[];s.seen={};s.spawnPolicy={maxEnemies:14};return s;}

// Healing herbs raise maximum HP only when already full.
let s=arena('tutorialDungeon'),herb=Kiri.Items.create('moonHerb',0,0,s.dungeonId);let result=Kiri.ItemActions.perform('drink',s,herb);assert.equal(s.player.maxHp,51);assert.equal(s.player.hp,51);assert(result.message.includes('最大HPが1'));
s=arena('tutorialDungeon');herb=Kiri.Items.create('starHerb',0,0,s.dungeonId);result=Kiri.ItemActions.perform('drink',s,herb);assert.equal(s.player.maxHp,52);assert.equal(s.player.hp,52);assert(result.message.includes('最大HPが2'));
s=arena('tutorialDungeon');s.player.hp=10;herb=Kiri.Items.create('moonHerb',0,0,s.dungeonId);result=Kiri.ItemActions.perform('drink',s,herb);assert.equal(s.player.maxHp,50);assert.equal(s.player.hp,35);assert(result.message.includes('HPが25回復'));

// Catalog size, required fields, dungeon restrictions and floor tables.
assert.equal(Kiri.EnemyCatalog.list.length,33);const fields=['id','name','role','floorRange','hp','attack','defense','exp','behaviorType','specialAbility','spawnWeight','maxPerFloor','dropRate','color','iconShape','description'];assert(Kiri.EnemyCatalog.list.every(d=>fields.every(k=>d[k]!==undefined)));const tutorialIds=new Set();for(let f=1;f<=10;f++)Kiri.EnemyCatalog.tableFor('tutorialDungeon',f).forEach(d=>tutorialIds.add(d.id));assert(tutorialIds.size===6);const normalIds=new Set();for(let f=1;f<=30;f++)Kiri.EnemyCatalog.tableFor('normalDungeon',f).forEach(d=>normalIds.add(d.id));assert(normalIds.size>=15);const mysteryIds=new Set();for(let f=1;f<=99;f++)Kiri.EnemyCatalog.tableFor('mysteryDungeon',f).forEach(d=>mysteryIds.add(d.id));assert.equal(mysteryIds.size,33);assert(Kiri.EnemyCatalog.tableFor('mysteryDungeon',2).every(d=>d.specialAbility==='none'));assert(!Kiri.EnemyCatalog.tableFor('tutorialDungeon',10).some(d=>['steal','weakenGear','split','phase'].includes(d.specialAbility)));assert.notDeepStrictEqual(Kiri.EnemyCatalog.tableFor('mysteryDungeon',2).map(d=>d.id),Kiri.EnemyCatalog.tableFor('mysteryDungeon',28).map(d=>d.id));assert(new Set(Kiri.EnemyCatalog.list.map(d=>d.color)).size>=15);assert(new Set(Kiri.EnemyCatalog.list.map(d=>d.iconShape)).size>=10);

// Special ability changes state and names the enemy in the log.
const random=Math.random;Math.random=()=>0;s=arena();s.player.power=8;let enemy=Kiri.Entities.createEnemy(6,{x:3,y:2},Kiri.Dungeons.get(s.dungeonId),'bileToad');s.enemies=[enemy];Kiri.Entities.enemyAct(s,enemy);assert.equal(s.player.power,7);assert(s.player.status.poison>0);assert(s.log[0].includes('ちから'));
s=arena();enemy=Kiri.Entities.createEnemy(20,{x:3,y:2},Kiri.Dungeons.get(s.dungeonId),'mirrorSeed');s.enemies=[enemy];Kiri.Entities.attack(s,enemy);assert(s.enemies.length>=2);assert(s.log.some(x=>x.includes('分かれた')));Math.random=random;

// Important status rendering replaces theme/music rows and shows current/max power.
let open=false;const elements={power:{textContent:''},statusGrid:{innerHTML:''},game:{getContext:()=>new Proxy({save(){},restore(){},translate(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},fill(){},arc(){},rect(){},ellipse(){},closePath(){}},{set:(o,k,v)=>(o[k]=v,true)})}};global.document={querySelector:q=>q==='#power'?elements.power:q==='#statusGrid'?elements.statusGrid:elements.game};Kiri.UI={draw:()=>{},toggleStatus:()=>{open=!open;},isStatusOpen:()=>open};load('js/enemy-renderer.js');load('js/stage10-ui.js');s=arena();s.player.power=3;s.player.maxPower=5;s.floorTheme='hidden';s.bgmThemeName='hidden';Kiri.UI.draw(s);assert.equal(elements.power.textContent,'3/5');let might=Kiri.Items.create('mightRing',undefined,undefined,s.dungeonId);might.equipped=true;s.player.equipment.ring=might;Kiri.UI.draw(s);assert.equal(elements.power.textContent,'6/8');Kiri.UI.toggleStatus(s);assert(elements.statusGrid.innerHTML.includes('状態異常'));assert(elements.statusGrid.innerHTML.includes('6 / 8'));assert(!elements.statusGrid.innerHTML.includes('階層テーマ'));assert(!elements.statusGrid.innerHTML.includes('想定曲調'));

// Old enemies gain catalog display and behavior fields.
const legacy=Kiri.State.fresh();legacy.enemies=[{x:4,y:4,hp:5,maxHp:5,power:2}];store[Kiri.Config.saveKey]=JSON.stringify(legacy);assert(Kiri.State.load());enemy=Kiri.State.data.enemies[0];assert(enemy.definitionId&&enemy.name&&enemy.color&&enemy.iconShape&&enemy.description);
console.log('stage 10 smoke: status, healing, catalog, visuals, abilities and migration passed');
