'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');global.window=global;global.Kiri={};global.localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};global.addEventListener=()=>{};let clock=100;global.performance={now:()=>clock};
function load(f){vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});}
['config','spawns','dungeons','themes','enemy-catalog','items','inventory','item-icons','state','map','visibility','combat-rules','entities','enemy-renderer','sprites','animation','item-actions','stage10-items','balance','traps','stairs','stage23-combat','stage22-rewards'].forEach(n=>load('js/'+n+'.js'));
function arena(){const s=Kiri.State.reset('normalDungeon');s.map=Array.from({length:24},()=>Array(32).fill(1));s.rooms=[{x:0,y:0,w:32,h:24,id:1}];s.player.x=2;s.player.y=2;s.player.facingDirection={dx:1,dy:0};s.enemies=[];s.groundItems=[];s.traps=[];s.inventory=[];s.spawnPolicy={maxEnemies:10};return s;}
function enemy(s,name,x,hp,exp){const e=Kiri.Entities.createEnemy(1,{x:x,y:2},Kiri.Dungeons.get(s.dungeonId),'dewMote');e.name=name;e.hp=hp;e.maxHp=hp;e.exp=exp;e.dropRate=0;e.spawnSleep=false;e.awake=true;s.enemies.push(e);return e;}

// Fire-breath herb deals 65-75 when drunk, restores 1 fullness, and retains shared EXP rewards.
const originalRandom=Math.random;Math.random=()=>0;
let s=arena(),foe=enemy(s,'石守り',5,65,8),herb=Kiri.Items.create('flameHerb',undefined,undefined,s.dungeonId);s.player.food=50;s.inventory=[herb];let result=Kiri.ItemActions.perform('drink',s,herb);assert(result.message.includes('石守りに65のダメージを与えた。'));assert(result.message.includes('石守りを倒した。8ポイントの経験値を得た。'));assert.equal(s.player.exp,8);assert.equal(s.player.food,51);
Math.random=()=>.999999;s=arena();foe=enemy(s,'石守り',5,100,8);herb=Kiri.Items.create('flameHerb',undefined,undefined,s.dungeonId);s.inventory=[herb];result=Kiri.ItemActions.perform('drink',s,herb);assert(result.message.includes('石守りに75のダメージを与えた。'));assert.equal(foe.hp,25);
Math.random=()=>0;s=arena();foe=enemy(s,'石守り',5,65,8);herb=Kiri.Items.create('flameHerb',undefined,undefined,s.dungeonId);s.inventory=[herb];s.groundItems=[Kiri.Items.create('nutBread',5,2,s.dungeonId)];result=Kiri.ItemActions.perform('drink',s,herb);assert.equal(s.groundItems.length,0);assert(result.message.includes('炎で燃え尽きた。'));
Math.random=()=>.999999;s=arena();foe=enemy(s,'石守り',5,100,8);herb=Kiri.Items.create('flameHerb',undefined,undefined,s.dungeonId);s.inventory=[herb];result=Kiri.ItemActions.perform('throw',s,herb);assert(result.message.includes('石守りに40のダメージを与えた。'));assert.equal(foe.hp,60);Math.random=originalRandom;

// A projectile victim remains drawable until the projectile arrival, then dies.
s=arena();foe=enemy(s,'まるスライム',5,1,2);const arrow=Kiri.Items.create('reedArrow',undefined,undefined,s.dungeonId);s.inventory=[arrow];Kiri.Animation.launch(s,'arrow',arrow);Kiri.ItemActions.perform('shoot',s,arrow);let deaths=Kiri.Animation.deathFrames(200),projectileDeath=deaths.find(d=>d.enemy.name==='まるスライム');assert(projectileDeath&&projectileDeath.pending);deaths=Kiri.Animation.deathFrames(350);projectileDeath=deaths.find(d=>d.enemy.name==='まるスライム');assert(projectileDeath&&!projectileDeath.pending&&projectileDeath.progress>0);

// Game-over music follows BGM settings, pauses the field track, and never resumes it.
let paused=false,plays=0;const field={get paused(){return paused;},pause(){paused=true;},play(){plays++;paused=false;}};global.document={querySelector:q=>q==='#bgmAudio'?field:null};Kiri.Audio={settings:()=>({enabled:true,volume:.35})};Kiri.Fanfare={cancelled:false,cancel(){this.cancelled=true;}};const param={setValueAtTime(){},exponentialRampToValueAtTime(){}};let started=0;const fake={currentTime:0,state:'running',destination:{},createOscillator:()=>({frequency:param,connect(){},start(){started++;},stop(){}}),createGain:()=>({gain:param,connect(){}})};load('js/stage23-audio.js');Kiri.GameOverMusic._setContext(fake);assert(Kiri.GameOverMusic.play());assert(paused);assert.equal(plays,0);assert(started>=10);assert(Kiri.Fanfare.cancelled);Kiri.GameOverMusic.stop();assert.equal(plays,0);Kiri.Audio.settings=()=>({enabled:false,volume:.35});assert.equal(Kiri.GameOverMusic.play(),false);

const html=fs.readFileSync('index.html','utf8'),css=fs.readFileSync('style.css','utf8'),sound=fs.readFileSync('js/sound.js','utf8');assert(html.includes('id="overlaySuspend"'));assert(html.includes('js/stage23-controller.js'));assert(css.includes('.overlay-actions'));assert(sound.includes('gameOver:[]'));
console.log('stage 23 smoke: herb damage logs, impact-ordered deaths, game-over music and choices passed');
