'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');global.window=global;global.Kiri={};const store={};global.localStorage={getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v,removeItem:k=>delete store[k]};global.addEventListener=()=>{};function load(f){vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});}
['config','spawns','dungeons','themes','enemy-catalog','items','state','stage8-state','map','visibility','combat-rules','entities','item-actions','stage10-items','balance','traps'].forEach(n=>load('js/'+n+'.js'));
function arena(id='normalDungeon'){const s=Kiri.State.reset(id);s.map=Array.from({length:24},()=>Array(32).fill(1));s.rooms=[{x:0,y:0,w:32,h:24,cx:16,cy:12}];s.player.x=2;s.player.y=2;s.player.hp=100;s.player.maxHp=100;s.player.facingDirection={dx:1,dy:0};s.stairs={x:30,y:22,type:'down'};s.groundItems=[];s.enemies=[];s.traps=[];s.seen={};s.spawnPolicy=Kiri.Spawns.policy(id,1,0);return s;}
let logs=[];Kiri.UI={draw:()=>{},showStairs:()=>{},closeStairs:()=>{},closeItemMenu:()=>{},showGameOver:()=>{},showEscape:()=>{},hideOverlay:()=>{},closeStatus:()=>{},toggleStatus:()=>{}};Kiri.Input={resetModes:()=>{}};Kiri.Audio={setTheme:()=>{}};load('js/game.js');

// Equipped arrows fire directly, hit, consume a turn and clear both slots at zero.
let s=arena(),arrow=Kiri.Items.create('reedArrow',undefined,undefined,s.dungeonId);arrow.quantity=1;arrow.equipped=true;s.inventory=[arrow];s.player.equipment.arrow=arrow;s.enemies=[Kiri.Entities.createEnemy(1,{x:5,y:2},Kiri.Dungeons.get(s.dungeonId),'chaser')];const hp=s.enemies[0].hp;assert(Kiri.Game.actions.shootArrow());assert(s.enemies[0].hp<hp);assert.equal(s.turn,1);assert.equal(s.player.equipment.arrow,null);assert(!s.inventory.includes(arrow));
s=arena();const turn=s.turn;assert.equal(Kiri.Game.actions.shootArrow(),false);assert.equal(s.turn,turn);assert(s.log[0].includes('装備していない'));

// Natural spawning respects time, cap, sight and distances.
s=arena('mysteryDungeon');s.spawnPolicy={nextSpawnTurn:25,naturalSpawnInterval:25,maxEnemies:14};s.turn=25;s.seen={'2,2':1};assert(Kiri.Spawns.tryNaturalSpawn(s));assert.equal(s.enemies.length,1);assert(Kiri.Util.distance(s.enemies[0],s.player)>8);assert(!s.seen[Kiri.Util.key(s.enemies[0].x,s.enemies[0].y)]);s.enemies=Array.from({length:14},(_,i)=>Kiri.Entities.createEnemy(1,{x:10+i%5,y:10+Math.floor(i/5)},Kiri.Dungeons.get(s.dungeonId),'chaser'));s.turn=s.spawnPolicy.nextSpawnTurn;assert.equal(Kiri.Spawns.tryNaturalSpawn(s),false);assert.equal(s.enemies.length,14);

// All behavior types exist; sleeper, fast, slow, ranged and thief have distinct actions.
assert.deepStrictEqual(Kiri.Entities.behaviors.sort(),['wander','chaser','sleeper','fast','slow','ranged','coward','thief'].sort());const oldRandom=Math.random;Math.random=()=>.5;
s=arena();let enemy=Kiri.Entities.createEnemy(1,{x:10,y:10},Kiri.Dungeons.get(s.dungeonId),'sleeper'),before=[enemy.x,enemy.y];s.enemies=[enemy];Kiri.Entities.takeEnemyTurns(s);assert.deepStrictEqual([enemy.x,enemy.y],before);assert.equal(enemy.awake,false);
s=arena();enemy=Kiri.Entities.createEnemy(1,{x:3,y:2},Kiri.Dungeons.get(s.dungeonId),'fast');s.enemies=[enemy];let playerHp=s.player.hp;Kiri.Entities.takeEnemyTurns(s);assert(s.player.hp<=playerHp-2);
s=arena();enemy=Kiri.Entities.createEnemy(1,{x:3,y:2},Kiri.Dungeons.get(s.dungeonId),'slow');s.enemies=[enemy];playerHp=s.player.hp;Kiri.Entities.takeEnemyTurns(s);assert.equal(s.player.hp,playerHp);Kiri.Entities.takeEnemyTurns(s);assert(s.player.hp<playerHp);
s=arena();enemy=Kiri.Entities.createEnemy(1,{x:7,y:2},Kiri.Dungeons.get(s.dungeonId),'ranged');s.enemies=[enemy];playerHp=s.player.hp;Kiri.Entities.takeEnemyTurns(s);assert(s.player.hp<playerHp);
Math.random=()=>.1;s=arena();enemy=Kiri.Entities.createEnemy(1,{x:3,y:2},Kiri.Dungeons.get(s.dungeonId),'thief');s.enemies=[enemy];s.inventory=[Kiri.Items.create('nutBread',undefined,undefined,s.dungeonId)];Kiri.Entities.takeEnemyTurns(s);assert.equal(s.inventory.length,0);assert(enemy.stolenItem&&enemy.fleeing);Math.random=oldRandom;

// Enemy statuses stop, randomize, slow/accelerate and poison as intended.
s=arena();enemy=Kiri.Entities.createEnemy(1,{x:3,y:2},Kiri.Dungeons.get(s.dungeonId),'chaser');enemy.status.sleep=2;s.enemies=[enemy];playerHp=s.player.hp;Kiri.Entities.takeEnemyTurns(s);assert.equal(s.player.hp,playerHp);enemy.status.sleep=0;enemy.effectSleep=0;enemy.status.bind=1;Kiri.Entities.takeEnemyTurns(s);assert(s.player.hp<playerHp);enemy.status.poison=4;let enemyHp=enemy.hp;Kiri.Entities.takeEnemyTurns(s);assert(enemy.hp<enemyHp);

// Every trap effect triggers and reveal scroll exposes traps.
s=arena();const trap=id=>({x:s.player.x,y:s.player.y,id:id,revealed:false});let result=Kiri.Traps.applyPlayer(s,trap('mistNeedle'));assert(s.player.hp<100);let powerBefore=s.player.power;result=Kiri.Traps.applyPlayer(s,trap('bileBloom'));assert.equal(s.player.power,powerBefore-1);assert.equal(s.player.status.poison||0,0);result=Kiri.Traps.applyPlayer(s,trap('dreamSeal'));assert(s.player.status.sleep>0);result=Kiri.Traps.applyPlayer(s,trap('spiralMark'));assert(s.player.status.confuse>0);result=Kiri.Traps.applyPlayer(s,trap('hungerMoss'));assert(s.player.food<100);result=Kiri.Traps.applyPlayer(s,trap('hollowFloor'));assert(result.descend);let gear=Kiri.Items.create('emberBlade',undefined,undefined,s.dungeonId);gear.equipped=true;s.inventory=[gear];s.player.equipment.weapon=gear;let bonus=gear.bonus;Kiri.Traps.applyPlayer(s,trap('dullingAsh'));assert.equal(gear.bonus,bonus-1);gear.equipped=false;s.player.equipment.weapon=null;s.inventory=[gear];Kiri.Traps.applyPlayer(s,trap('scatterSnare'));assert.equal(s.inventory.length,0);assert(s.groundItems.includes(gear));let scroll=Kiri.Items.create('trapScroll',undefined,undefined,s.dungeonId);s.inventory=[scroll];Kiri.ItemActions.perform('read',s,scroll);assert.equal(s.vision.traps,true);

// Tutorial opening floors remain trap-free and old saves gain behavior/status fields.
for(let floor=1;floor<=3;floor++){s=Kiri.State.reset('tutorialDungeon');s.floor=floor;Kiri.Game.buildFloor();assert.equal(s.traps.length,0);}const legacy=Kiri.State.fresh();legacy.enemies=[{x:4,y:4,hp:5,maxHp:5,power:1}];legacy.stairs={x:5,y:5};delete legacy.spawnPolicy;store[Kiri.Config.saveKey]=JSON.stringify(legacy);assert(Kiri.State.load());assert.equal(Kiri.State.data.enemies[0].behaviorType,'chaser');assert(Kiri.State.data.spawnPolicy);

// F key reaches the equipped-arrow action.
let keyHandler=null,shots=0;global.addEventListener=(t,f)=>{if(t==='keydown')keyHandler=f;};const hidden={classList:{contains:()=>true},addEventListener:()=>{}};global.document={querySelector:q=>hidden};Kiri.UI.isStairOpen=()=>false;Kiri.UI.isStatusOpen=()=>false;Kiri.Input={init:()=>{}};load('js/stage9-input.js');Kiri.Input.init({shootArrow:()=>shots++});keyHandler({key:'f',preventDefault:()=>{}});assert.equal(shots,1);
console.log('stage 9 smoke: arrows, spawning, behaviors, statuses and traps passed');
